### ISSUE TITLE
Unity demo is firing exceptions

### ISSUE THREAD

**Issue by molocai** [YarnSpinnerTool/YarnSpinner#105]
Re-opening #99 

The issue is basicaly the same I just wanted to have a fresh open issue for this.
I'd be happy to fix this if pointed towards the right direction. :)

**Comment by molocai** [comment]
Hello McJones, yes version 0.9.9 works fine as far as I know!

**Comment by McJones** [comment]
ah right-oh, thanks for checking.
I guess for now use that version and we'll have to look into this a bit further.

**Comment by McJones** [comment]
There hasn’t been any activity on this in a while and the example code has undergone a lot of changes so I am closing this issue.
If the issue reappears please open a new issue.
