### ISSUE TITLE
Unity demo doesn't work correctly if text speed is set to 0s instead of 0.025s

### ISSUE THREAD

**Issue by catherineomega** [YarnSpinnerTool/YarnSpinner#114]
It's possible I'm misreading the intent of the script, but:

To reproduce:

1. Import the Unity Demo.
2. Open the YarnSpinnerBasicExample scene.
3. Edit the "Dialogue" object.
4. Change "Text Speed" to 0.
5. Run.

Observed behaviour:
"A: Hey, I'm a character in a script!" displays correctly.
"B: And I am too! You are talking to me!" does not display.

Expected behaviour: 
Lines of dialogue should display in order like they do when there's a time specified rather than being skipped.

**Comment by desplesda** [comment]
This appears to be fixed as of v1.1. Closing!
