### ISSUE TITLE
WebGL Dialogue.Run Stopping and Scrolling Speed Inconsistent Across Win/Mac

### ISSUE THREAD

**Issue by eviesmash** [YarnSpinnerTool/YarnSpinner#119]
Hello SecretLabbers!

I'm trying to create a WebGL build of my game and I use dialogue with the YarnSpinner in my level selection. When the game gets to that scene, with the Debug on, I get this message.
"Dialogue.Run was called, but no program was loaded. Stopping."
The dialogue windows don't appear and it appears to not work. The exact same game runs in the Editor and on Windows/Mac.

On another note, the text scrolling speed seems to only affect Windows builds. Testing on Mac the speed doesn't change no matter how small I make the scrolling speed.

Thank you for looking into the issue!
~Evie

**Comment by eviesmash** [comment]
Bump

**Comment by Kadelam** [comment]
Newtonsoft.JSON uses System.Reflection.Emit which is not available in ahead of time compile platforms, such as WebGL, along with a dozen other different platforms, hence your error.

**Comment by McJones** [comment]
There hasn’t been any activity on this in a while so I am closing this issue.
If the issue reappears please open a new issue.
