### ISSUE TITLE
Syntax should have an indication of which character is speaking

### ISSUE THREAD

**Issue by lordmortis** [YarnSpinnerTool/YarnSpinner#121]
As discussed [here](https://narrativegamedev.slack.com/archives/C5F1PEGER/p1523331393000084) we should officially support syntax like: 
```
Yzma: Pull the lever Kronk
Yzma: Wrong lever!!!
Kronk: Uh?
```

But the runtime should give back both the entire text line (i.e. the string `Yzma: Pull the lever Kronk`) and also the character and what they are saying (i.e. the character `Yzma` and the string `Pull the lever Kronk`)

**Comment by netherchef** [comment]
I would love to have this for jumping between characters mid-dialogue!

**Comment by desplesda** [comment]
Following up on this: this is something we're definitely going to add to the language spec.

**Comment by desplesda** [comment]
Linked issue: https://github.com/YarnSpinnerTool/YarnSpinner/issues/247

**Comment by desplesda** [comment]
This feature has now been merged into `develop`, so I'll close the issue now!
