### ISSUE TITLE
Function calls have a verb now

### ISSUE THREAD

**Issue by lordmortis** [YarnSpinnerTool/YarnSpinner#122]
To make for more explicit/easier parsing the syntax should be
`<<func whoIsTheFunkyDoctor("who") >>`

**Comment by TheMartianLife** [comment]
Interesting. We're having some discussion on it, but implementation would likely have to be rolled in while we're doing other breaking changes. We'll keep you updated!

**Comment by desplesda** [comment]
This was implemented in v1.0. Closing this issue now!
