### ISSUE TITLE
clearer definition of commands and allowing for expansion etc.

### ISSUE THREAD

**Issue by lordmortis** [YarnSpinnerTool/YarnSpinner#125]
Commands are now anything that's not:
 - a function call on it’s own (i.e. `<< {func} funcCall(arg1, arg2) >>`)
 - a variable set ( `<< {set} $varName = 1 >>` or `<< {set} $varName += 1 >>`)
 - isn’t one of the `if` verbs (`if`, `elseif`, `elsif`, `else` or `endif`)

Commands don't have a return from engine to yarn-land but function calls do

Commands are sent from the runtime as an array of values (i.e. `<< kronk pull the lever >>` is sent as a 4 part array containing `kronk`, `pull`, `the` and `lever`

Commands can have variable substitution (i.e. ```
<< set $leverColor = 'yellow'>>
<< kronk pull the $leverColor lever >>
```
sends `kronk`, `pull`, `the`, `yellow`, `lever` to the engine

commands can have expression evaluation (i.e. ```
<< kronk pull the yellow lever (3+1) times >>
```
sends `kronk`, `pull`, `the`, `yellow`, `lever`, `3`, `times` to the engine

**Comment by desplesda** [comment]
Documentation for commands has been updated on the [Yarn Spinner site](https://yarnspinner.dev/docs/unity/working-with-commands/), so I'll close this issue now. Thank you!
