### ISSUE TITLE
YarnSpinnerConsole crashes when running genstrings on test script

### ISSUE THREAD

**Issue by Blecki** [YarnSpinnerTool/YarnSpinner#128]
Unhandled Exception: System.InvalidOperationException: In file ..\..\..\Tests\TestCases\Substitution.node: Error reading node Start: expect_line is not a valid function.

**Comment by McJones** [comment]
Unfortunately the Console got a bit behind the core of the project.
We are working on updating the console but that will require a hefty rewrite of the Console so it won’t happen until after 1.1 release.

I am closing this now but if you have any other issues with the console please mention them in issue #175 to keep it all in one place.
