### ISSUE TITLE
Dialog is skipping every other line

### ISSUE THREAD

**Issue by Krazzdaxx** [YarnSpinnerTool/YarnSpinner#131]
I'm having trouble writing dialog with Yarn right now. 

Yousaf: I'm OK. I'm just getting packed up.
Player: Why are you packing up you things?
Yousaf: I'm getting tired of staying here and I would like to go back home.
Player: Oh OK.

When I run this dialog it seems to be skipping every other line.
This snippet will only run:
Yousaf: I'm OK. I'm just getting packed up.
Yousaf: I'm getting tired of staying here and I would like to go back home.

It seems to be skipping every other line. Does anybody know whats the issue or what I am doing wrong.

**Comment by JLevstein** [comment]
Hey @Krazzdaxx, it'll help us help you if you post a little bit of code showing how you're parsing the Yarn script.

My gut is saying that it's something to do with how you're reading for who is speaking though.

**Comment by Haru-u** [comment]
Hi! I'm also having a similar problem. Some lines get skipped, and some options get displayed one after the  other. One of my scripts is written in portuguese, so maybe there's some problem parsing the special characters? I was lazy and used the code from the yarn spinner demo. Also the game's a monolgue, so I guess it wouldn't be having problems in the npc x player sphere.

**Comment by Goombario** [comment]
When I had this issue it was because on the new dialogue started on the same frame as the old one going away, so when it looked for a keypress it essentially received it twice. I solved this by having the check happen in the update loop and having it turn off when the dialogue line started.

**Comment by Appleguysnake** [comment]
This problem happens with the ExampleDialogUI script, in the RunLine coroutine whenever `textSpeed == 0`, for the reason @Goombario explained. 

I fixed it in the example script by just adding a wait for the end of the frame:

```
            // Wait for any user input
            while (Input.anyKeyDown == false) {
                yield return null;
            }

            yield return new WaitForEndOfFrame();  //just this line

            // Hide the text and prompt
            lineText.gameObject.SetActive (false);
```

**Comment by McJones** [comment]
There hasn’t been any activity on this in a while so I am closing this issue.
If the issue reappears please open a new issue.
