### ISSUE TITLE
If Check Arrangements affect Results

### ISSUE THREAD

**Issue by netherchef** [YarnSpinnerTool/YarnSpinner#134]
```
<<if $ActiveQuest is "Dinner">>
[[Dinner]]
<<elseif $ActiveQuest is null>>
[[Idle]]
<<endif>>
```
The above seems to ignore the ```elseif```.

```
<<if $ActiveQuest is null>>
[[Dinner]]
<<elseif $ActiveQuest is "Dinner">>
[[Idle]]
<<endif>>
```
This on the other hand, works fine.

Why is this?

**Comment by desplesda** [comment]
Reproduced in 06b66219bf753ee6097832e528d75f7c5e63110d, and appears to be linked to https://github.com/YarnSpinnerTool/YarnSpinner/issues/167 - nulls are compared in a confusing way, and that's producing this behaviour.

**Comment by desplesda** [comment]
This behaviour no longer exists as a result of work done in the `develop` branch; as a result, I'll close this issue. Thanks for filing it!
