### ISSUE TITLE
WebGL JSON error

### ISSUE THREAD

**Issue by jonschwa** [YarnSpinnerTool/YarnSpinner#135]
I am experimenting with this library in a new Unity project, but when I build as webGL, none of the dialog works and I see this error:

```
NotSupportedException: /Applications/Unity/Unity.app/Contents/il2cpp/libil2cpp/icalls/mscorlib/System.Reflection.Emit/DynamicMethod.cpp(19) : Unsupported internal call for IL2CPP:DynamicMethod::create_dynamic_method - System.Reflection.Emit is not supported.
```

I saved my script as XML and rebuilt, which did actually "work" (albeit with all the XML nodes output as text 😂 ), but this definitely means the issue is exclusive to JSON. I'm pretty new to Unity and C# in general, but I would be happy to help out any way I can.

-Jon

**Comment by ecmjohnson** [comment]
Hey Jon, you're hitting up against the fact that the build backend for WebGL (IL2CPP) doesn't support any methods in the `System.Reflection.Emit` namespace (see [this page](https://docs.unity3d.com/Manual/ScriptingRestrictions.html)). I think that methods in this namespace are used in the JSON parser.

Were you able to successfully work around this issue and, if so, how? I now need to do the same thing

**Comment by ecmjohnson** [comment]
Actually, there's a no code required workaround/fix I found from **techknight** on the Slack: disable the JSON parser included with YarnSpinner and replace it with [this one](https://www.assetstore.unity3d.com/#!/content/11347).

Disabling the Newtonsoft parser is as simple as unchecking "Any Platform" in the inspector:
![newton_disable](https://user-images.githubusercontent.com/6766142/46898749-d83ba980-ce59-11e8-8d49-93f83b0273f9.PNG)

Then simply get the one linked above that uses a different library depending on the platform and allows building for ahead of time compilation platforms.

**Comment by mintsticks** [comment]
Hey ECM, how did you go about swapping the json parser used by Yarn Spinner?

**Comment by desplesda** [comment]
We removed JSON support (and therefore the dependency on Newtonsoft.Json) in 20ed20, as per #173, so this should be resolved!
