### ISSUE TITLE
YarnSpinnerComplexExample user controls undocumented in release

### ISSUE THREAD

**Issue by fragmental** [YarnSpinnerTool/YarnSpinner#136]
It took me some time to discover that the player is controlled with the arrows. And dialogue is started by pressing space in front of a character.  When I first loaded up the scene, there were no instructions on the screen so I just assumed it was broken, and ignored it for a while.

**Comment by McJones** [comment]
With the changes to the examples Complex Example no longer exists so I am closing this issue.
There are still a lot of docs work to be done but this specific one doesn’t exist.
