### ISSUE TITLE
Getting the name of a target chosen Node

### ISSUE THREAD

**Issue by fragmental** [YarnSpinnerTool/YarnSpinner#138]
I know that I can get the name of the current Node with DialogueRunner.dialogue.currentNode or DialogueRunner.currentNodeName, but I need to find the name of a target node in the options, the same way you can get the Option text from Yarn.Options.

I'm willing to make the necessary changes myself, but I'm not really a good enough programmer to fully understand what changes I need to make.

A typical use case for this might be to automatically check against visited nodes if a person wanted to automatically hide visited nodes using something like `if (dialogue.visitedNodeCount.ContainsKey(dialogue.currentNode) == false)` , instead of using the inbuilt yarn function, in their yarn script, for every option like `<<if visited("NodeName") is false>>`.  

The reason I need it is that I have a point pool (int) that I'm checking against, and I want to block the execution of any option for a node that hasn't been visited yet.  So a user can choose options they've already chosen without spending any points, but will need to spend points to progress to options they haven't chosen yet.

**Comment by fragmental** [comment]
I have a working solution for this. I'll submit a pull request after I clean it up a little.

**Comment by fragmental** [comment]
#139 implementation

**Comment by desplesda** [comment]
Closing, because the associated PR #139 was merged. Thank you!
