### ISSUE TITLE
Problem with creating if statements with functions

### ISSUE THREAD

**Issue by kipswinstudent** [YarnSpinnerTool/YarnSpinner#153]
I'm having some problems creating Unity functions and calling on them from Yarn. 
I've copied the example function from [here](https://github.com/thesecretlab/YarnSpinner/blob/a750125ab4325e9cf2ceb484b7f7ab08a4d1baff/YarnSpinnerTests/LanguageTests.cs#L30) into the void Start () of DialogueRunner.cs an attempt to work out the issues. 

Here is the Yarn script calling on this function:
`OK, this is filler dialogue.` 
`<<if (last_value(1, 2, 3) == 3)>>`
`    OK, that worked`
`    [[Repeat|AddCosts]]`
`<<endif>>`
`no you broke it.`

When run in Unity this generates the error "Operation is not valid due to the current state of the object"

edit: On further digging, this could be a bracketing issue. 
If I change the second line to:

`<<if last_value (3) == 3>>`

I instead get the error:  "last_value is not a valid function"

**Comment by McJones** [comment]
that is a C# error message, it is normally associated with a stack trace as well, could you also post the stack trace that came along with the error that way we can try and work out what is happening.

**Comment by McJones** [comment]
There hasn’t been any activity on this so I am closing it.
Please open a new issue if the problem persists.
