### ISSUE TITLE
feature request: copy YarnSpinnerConsole source text processing functions into YarnSpinnerUnity

### ISSUE THREAD

**Issue by radiatoryang** [YarnSpinnerTool/YarnSpinner#165]
from Localisation 'YarnSpinnerConsole.exe' standalone #83:

> I would like this too, building it on windows is a mess!
Monodevelop isn't available on windows so i have to build that too!
Please do this, i wasn't able to get it working after like a day of trying 

as agreed upon before, we probably shouldn't expect authors to compile YarnSpinnerConsole, much less expect them to learn command line console stuff even with pre-built YarnSpinnerConsole binaries

standalone YarnSpinnerConsole (with GUI) would be cool, but also, if you just expose this functionality in YarnSpinnerUnity then people could potentially build editor plugins to support authors... (cough cough!)

so... I'd deeply appreciate if the line-tagging / localization file generation stuff was copied into the main Unity Yarn Spinner library so that Unity Editor tools can hook into it (for the convenience of authors!)... just something like ``string[] TagYarnTextLines(string[] textFromYarnTxtFiles)`` or even ``bool TryToAddTagsToAllFiles(string[] filePaths)`` would be so great, and hopefully not require much change from [LineAdder.cs](https://github.com/thesecretlab/YarnSpinner/blob/master/YarnSpinnerConsole/LineAdder.cs)?

**Comment by desplesda** [comment]
This has been included as part of the 1.0 release, so I'm closing this issue. Thanks for filing the feature request!
