### ISSUE TITLE
Symbols Discussion: Language Spec and Reserved Characters

### ISSUE THREAD

**Issue by TheMartianLife** [YarnSpinnerTool/YarnSpinner#168]
Due to the characters used within the definition of Yarn itself, behaviours in using characters such as <>[]{}|:\s#$ in node titles or variable names are undefined. It is not that they necessarily *won't work*, but that they sometimes do or don't or have totally weird behaviours (such as in #162, #149, #56 and more).

These should be explicitly disallowed, including both a) documenting this clearly in a Language Spec document and b) throwing intelligent errors if encountered.

...(even though this would have to be at runtime at the moment bc no compile step and thus errors may get missed depending on paths, so maybe this might be more of a consideration for write-time things like editor extensions in the future).

**Comment by radiatoryang** [comment]
FYI as of v0.6.0, Merino now strips out these reserved characters from node titles. Here's the regex if it's useful for anyone working on editor stuff or tools: https://github.com/radiatoryang/merino/blob/a70d9e1b49a1d106db046c4c189c2de40bdcec6d/Assets/Merino/Editor/Scripts/MerinoCore.cs#L14

**Comment by desplesda** [comment]
Commit 368a54fad6 makes the compiler use this regex when parsing node titles. Thanks, @radiatoryang, and thanks @TheMartianLife for the bug report!
