### ISSUE TITLE
Difficulty running YarnSpinnerConsole

### ISSUE THREAD

**Issue by MightbeMagic** [YarnSpinnerTool/YarnSpinner#175]
I was attempting to run the console project, but continuously received errors related to not having a file to look at, and no commands entered. 

I manually entered a "run" command into args through code, and added a file directly to options.files, but wanted to know the intended way of getting the console project to run files and commands since this didn't feel right. I couldn't find any entry point for files being added to options in the console project.

**Comment by McJones** [comment]
The console got a bit behind with the core and unity versions and we are planning on rewriting it soon to be compatible with 1.x YarnSpinner soon.

**Comment by McJones** [comment]
The console has now been split off into its [own repo](https://github.com/YarnSpinnerTool/YarnSpinner-Console) and all future development of the console will be going on there.
While it feature set isn't as complete as the older console it at least works.

I am closing this issue, feel free to open new issues around the console in its repo.
