### ISSUE TITLE
YarnSpinnerConsole - cannot use "taglines" with custom functions

### ISSUE THREAD

**Issue by adamgryu** [YarnSpinnerTool/YarnSpinner#176]
When I try to use the "taglines" console command, it says "skipping file due to compilation errors."

To debug the problem, I had to add stack trace logging to the console tool (the given error message was not helpful). The program fails when it encounters a custom function of mine.

I poked around the code a bit more, and found this in Main.cs:

```
            // Note that we're passing in with a null library - this means
            // that all function checking will be disabled, and missing funcs
            // will not cause a compile error. If a func IS missing at runtime,
            // THAT will throw an exception.

            // We do this because this tool has no idea about any of the custom
            // functions that you might be using.

            Dialogue d = new Dialogue(null);
```

However, the constructor for Dialogue looks like this...

```
        public Dialogue(Yarn.VariableStorage continuity) {
            this.continuity = continuity;
            loader = new Loader (this);
            library = new Library ();

            library.ImportLibrary (new StandardLibrary ());
```

It seems like the library is set regardless of constructor input. This causes GetFunction() to fail during the parser step.

I'm able to hack around this problem for the moment, but I'm not sure what the proper fix should look like.

**Comment by desplesda** [comment]
Huh, two things:

1. That looks like a silly mistake on my part. When running under diagnosis, it’s not possible for the stand alone console app to know what functions would be available during gameplay, so I decided to mark “null” as “don’t know”. Then I appear to have promptly forgotten that that was my intention.

2. Better compilation errors are clearly needed.

TBH, the real solution here is to merge the command line tool into the runtime, and expose its features via the Unity window.

**Comment by desplesda** [comment]
This is now exposed as part of the Unity integration; I'm going to close this issue, because the initially reported problem of 'adding tags to scripts that use custom functions' is addressed by this. I'd still like to improve command line situation, but that'll be a different issue. Thanks for the bug report!

**Comment by adamgryu** [comment]
Thank you for your work on this great tool!! :)
