### ISSUE TITLE
"The node null does not exist" error when running compiled program

### ISSUE THREAD

**Issue by giulianob** [YarnSpinnerTool/YarnSpinner#178]
I'm running the following command and getting the error "The node null does not exist"
```
YarnSpinnerConsole.exe run -d -s Sally -T sally.yarn_lines.csv sally2.yarn.yarn.bytes
Note: Running node Sally
Warning: Yarn Error: The node null does not exist.
Player: Hey, Sally.
Sally: Oh! Hi.
Sally: You snuck up on me.
Sally: Don't do that.
Warning: Yarn Error: The node null does not exist.
Warning: Yarn Error: The node null does not exist.
Options:
1. Anything exciting happen on your watch?
2. See you later.
```

The steps I took
1) Run taglines on the script
2) Run genstrings to create the CSV
3) Compile the program
4) Run the command above.

It works fine if I just run the script without pre-compiling it first. It looks like the error happens on the condition lines such as `<<if not visited("Sally.Watch")>>` because it doesn't seem to find the node correctly.

**Comment by McJones** [comment]
The console has a bunch of quirks as it is quite a bit out of date, we are working on updating it soon.

**Comment by McJones** [comment]
Actually on reflection to keep the issues relating to the console all together I am closing this now but if you have any other issues with the console please mention them in issue #175 to keep it all in one place.
