### ISSUE TITLE
Semantic predicate in ANTLR lexer is non-portable to C++

### ISSUE THREAD

**Issue by josh04** [YarnSpinnerTool/YarnSpinner#179]
There's a semantic predicate in [YarnSpinnerLexer.g4:117](https://github.com/thesecretlab/YarnSpinner/blob/7d02da61ddef457f190835b16eec21643ee1fffe/YarnSpinner/ANTLR/YarnSpinnerLexer.g4#L117) which inlines a call to `_input.LA(1)`. When using ANTLR to produce a C++ lexer/parser, this results in a compile error as `_input` is represented as a pointer (`CharStream *`), rather than a reference, in the C++ interface. Changing the outputted predicate to read `_input->LA(1)` in `YarnSpinnerLexer.cpp:65` fixes the issue for me. As I don't have much experience with ANTLR, I'm incapable of suggesting a more general fix myself.

I saw in the [ANTLR notes](https://github.com/thesecretlab/YarnSpinner/blob/master/Documentation/antlr-notes-and-discussion.md) that portability is not currently supported for the ANTLR lexer/parser, and there is a comment alongside the predicate indicating that it is already targeted for removal. As well, the fix is fairly straightforward for the C++ interface so I don't think this is a particularly pressing matter, but I wanted to highlight it specifically in case anyone else hits the same issue.

Thanks for your work on a very useful library!

**Comment by McJones** [comment]
yeah the semantic predicate is unfortunately non-portable but as you said both intended to be removed and relatively easy to fix on a language by language basis.

Gone close this issue now, but feel free to re-open if you hit any other issues.
