### ISSUE TITLE
Announcement: This repo is moving to a new URL

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnSpinner#180]
Hi, everyone!

Since it was first started, Yarn Spinner has been a project that's been primarily run by Secret Lab, an Australian game dev studio that we run. As a result, the repo has been a part of our @thesecretlab organisation.

We have a number of plans for making Yarn Spinner bigger, better, and more useful to a wider number of people. As part of our plans to broaden the Yarn Spinner ecosystem, we've created a new organisation on GitHub, @YarnSpinnerTool. We plan on migrating this repo over to https://github.com/YarnSpinnerTool/YarnSpinner, where it and other Yarn-related projects will live.

**What does this mean for you?**

The entire project will be moved over in the next day or two. This is a direct transfer of the repo, so the git history, issues and wiki will all be moved as well.

The only way that this affects you is if you have a local copy of the repo, and want to be able to keep it in sync with the version on GitHub. If that's the case, you'll need to update your remotes:

```bash
git remote rm origin
git remote add origin https://github.com/YarnSpinnerTool/YarnSpinner
```

**Got questions?**

If you want more info on what's happening, please post in this issue, talk to us on twitter (we're [@YarnSpinnerTool](https://twitter.com/YarnSpinnerTool), or email me at yarnspinner@secretlab.com.au.

Thank you so much for using Yarn Spinner. We can't wait to show you what happens next.

**Comment by ScrapGames** [comment]
Thanks for the update! Looking forward to what the future has for YarnSpinner!
