### ISSUE TITLE
Mid-dialogue save point/serialization of postion feature request

### ISSUE THREAD

**Issue by roxygen** [YarnSpinnerTool/YarnSpinner#181]
Ability to save, serialize and restore dialogue from some point before it's end.

**Comment by desplesda** [comment]
This is a cool idea, and something that a few people have asked. I'll consider adding it to our future plans!

**Comment by desplesda** [comment]
This feature is now actively being worked on; progress is being tracked as part of #242. I'll close this issue so we don't have multiple items for the same task, but please subscribe to #242 if you want to stay updated on progress!
