### ISSUE TITLE
YarnSpinnerConsole - IndexOutOfBounds taglines

### ISSUE THREAD

**Issue by pjarnfelt** [YarnSpinnerTool/YarnSpinner#182]
In a new build, when I try to do the taglines command, I get an IndexOutOfBounds error

Indeed, the line number each line gets is not based on the node, but on the entire yarn file...
I based my tests on this yarn file:
[taglinestest.yarn.txt](https://github.com/YarnSpinnerTool/YarnSpinner/files/3676007/taglinestest.yarn.txt)

The error happens in the LineAdder Script around this point:
```
var lines = nodeInfo.body.Split(new string[] { "\r\n", "\n" }, StringSplitOptions.None);

Console.WriteLine("Node: " + line.Value.nodeName);
Console.WriteLine("Get line number: " + line.Value.lineNumber);
Console.WriteLine("All lines length: " + lines.Length);
// Get the original line
var existingLine = lines[line.Value.lineNumber - 1];
Console.WriteLine("Existing Line: " + lines.Length);
```

I've added Console.WriteLine for debugging purposes and get:
```
Node: Node1
Get line number: 6
All lines length: 1
```
"Existing Line" is not printed since the out of bounds happens there

**Comment by McJones** [comment]
The YarnSpinnerConsole got a bit out of date with the project and has a lot of issues.
We are going to have to basically rewrite a lot of console so it won’t be happening until 1.1 is out.

I am going to close this issue (and any related console issues) all under issue #175 please move any discussion to there.
