### ISSUE TITLE
YarnSpinner dependency redefines a core type from the system namespace

### ISSUE THREAD

**Issue by Schroedingers-Cat** [YarnSpinnerTool/YarnSpinner#185]
The included dependency to CsvHelper introduces a redefinition of a core type in the system namespace so that other third party libraries or custom project code using `System.Reflection.TypeInfo` become ambiguous. 

Updating the CsvHelper library to the latest version 12.2.2 fixes this problem but likely introduces new problems if the project is using NUnit.  

More details about this can be [found here](https://support.ludiq.io/communities/41/topics/4230-privatereflectiondynamicobjectbase-error-in-unity-201920f1#comment-12018)

**Comment by desplesda** [comment]
Fixed as of v1.0.0.
