### ISSUE TITLE
Yarn doesn't function in the final build 

### ISSUE THREAD

**Issue by clchung** [YarnSpinnerTool/YarnSpinner#186]
This might be a simple fix but I'm having issues with building. Yarn works fine within Unity but doesn't run in the final build. All I am doing is building the scenes as usual, am I missing a step?

**Comment by desplesda** [comment]
Hi! Are you seeing some kind of error in the console?

**Comment by clchung** [comment]
> Hi! Are you seeing some kind of error in the console?

Hi! No, the console says the build has run successfully. Everything within Unity works fine. Would I have to build Yarn as well in some way or add it to the project folder?

**Comment by desplesda** [comment]
You don't need to build Yarn Spinner, since its DLLs are included in your build by Unity.

Can you elaborate a little more on what you're seeing? Like, when you start dialogue, do you see anything appear in your build's log? (See https://docs.unity3d.com/Manual/LogFiles.html for information on how to access the Player log from your game.)

**Comment by clchung** [comment]
> You don't need to build Yarn Spinner, since its DLLs are included in your build by Unity.
> 
> Can you elaborate a little more on what you're seeing? Like, when you start dialogue, do you see anything appear in your build's log? (See https://docs.unity3d.com/Manual/LogFiles.html for information on how to access the Player log from your game.)
Ah, thank you! I'm not that experienced so I didn't even know how to look at the player log. It just turned out to be a Unity problem, given this error:
`PlatformNotSupportedException: Operation is not supported on this platform.` 
Followed by a lot of JSON related lines, so so I just changed the API compatibility level to .NET 4x. Thanks a ton for your help, I was at a total loss.
