### ISSUE TITLE
Commands will not run depending on GameObject existence

### ISSUE THREAD

**Issue by janmaslov** [YarnSpinnerTool/YarnSpinner#190]
Recently noticed a bug that makes some commands not run.

I have a Yarn script without dialogue that I use to set up a cutscene upon first visit of the scene:
```
title: [Start]
tags: 
colorID: 0
position: 0,0
---
<<if not $visited_l01 >>
	<<set $visited_l01 to true>>
	<<createcutscene cutscene000>>
	<<playcutscene cutscene000>>
<<endif>>
===
```
The first of the two custom commands will spawn a prefab (named _cutscene000_) that contains everything needed for the cutscene. The second one will go to that newly spawned object's PlayableDirector for the Timeline-based cutscene and play it. The second command is not executed.

I've tracked it down to an error in _DispatchCommandToGameObject_ in _DialogueRunner.cs_. At the end of the method the variable _wasValidCommand_ is defined and not used when returning from the method. The _methodFound_ boolean to be returned is always returned as true, which means that the call will not be passed on to my handler definition that is not in any Component on the target GameObject.

This code block:
```
var wasValidCommand = numberOfMethodsFound > 0;

if (startedCoroutine) {
	// Signal to the Dialogue that execution should wait. 
	return (true, Dialogue.HandlerExecutionType.PauseExecution);
} else {
	// This wasn't a coroutine, so no need to wait for it.
	return (true, Dialogue.HandlerExecutionType.ContinueExecution);
}
```

Should be this:
```
var wasValidCommand = numberOfMethodsFound > 0;

if (startedCoroutine) {
	// Signal to the Dialogue that execution should wait. 
	return (wasValidCommand, Dialogue.HandlerExecutionType.PauseExecution);
} else {
	// This wasn't a coroutine, so no need to wait for it.
	return (wasValidCommand, Dialogue.HandlerExecutionType.ContinueExecution);
}
```

**Comment by desplesda** [comment]
This was fixed in 351ef48, which shipped as part of v1.0.2. Thanks for reporting it!
