### ISSUE TITLE
Parsing duration of wait command will return differently in different system locales

### ISSUE THREAD

**Issue by janmaslov** [YarnSpinnerTool/YarnSpinner#191]
Small oversight. When using the built-in _wait_ command to wait some time before progressing in the current script, the duration is parsed differently depending on your system locale. On a German install of Windows a duration of _18.5_ is parsed as _185_ because the parser is locale-aware and will not interpret a dot as a decimal separator. It will only do so with a comma.

Can be fixed by altering the _float.TryParse_ call in the _HandleWaitCommand_ method in _DialogueRunner.cs_.

This line:
```
if (float.TryParse(durationString, out var duration) == false) {
```

Should be this:
```
if (float.TryParse(durationString, System.Globalization.NumberStyles.AllowDecimalPoint, System.Globalization.CultureInfo.InvariantCulture, out var duration) == false) {
```

This will prevent the parser from parsing the duration string according to the current locale, which will make it parse dots as decimal separators correctly. But there might be a more elegant way.

**Comment by desplesda** [comment]
Fixed in 4043400.
