### ISSUE TITLE
Empty space for node title can cause very embarrassing mistake

### ISSUE THREAD

**Issue by Kicory** [YarnSpinnerTool/YarnSpinner#192]
This is not a bug, but I thought it was bug and spent much time for this problem.

The Yarn Editor auto completes [[ and ]], and there's one white space after the linked node title.
![image](https://user-images.githubusercontent.com/42833717/72661691-a207b500-3a20-11ea-990f-0de40dd36b52.png)

I thought the whitespace will be trimmed, so I wrote like this...
![image](https://user-images.githubusercontent.com/42833717/72661726-25c1a180-3a21-11ea-898f-78416ae6092e.png)

Yarn parser in Unity cannot find my 'first' node because the parser tried to find ' first '. I thought it was fatal bug, but it was just a silly mistake.

I don't think Yarn parser should auto-trim the white space in node title, but it should warn about that. It's just adding one line code, but I think it will be very useful.

Edit: little spell change

**Comment by McJones** [comment]
Yeah I agree the parser should either warn or just straight up strip out the white space.
Not sure at this stage which is the better option but we do have to go with one of them

**Comment by desplesda** [comment]
Stripping makes more sense here. Node names aren't allowed to have spaces in them, so there's no ambiguity if we just trim spaces off the start and end.
