### ISSUE TITLE
Missing scripts on "Dialogue" prefab causing issues in example scene

### ISSUE THREAD

**Issue by robbiesaurus** [YarnSpinnerTool/YarnSpinner#209]
I've just downloaded the 1.0.3 release from the releases page and started up a 2D template project as advised. When pressing play I get the following message:

`NullReferenceException: Object reference not set to an instance of an object
Yarn.Unity.DialogueUI.Awake () (at Assets/YarnSpinner/Scripts/DialogueUI.cs:86)`

I looked at the Dialogue prefab and have found that all the scripts attached to "Dialogue Canvas" and its children are all missing with the message
`The associated script can not be loaded.
Please fix any compile errors and assign a valid script.`

However there are no compile errors - the project starts after pressing play and Visual Studio is reporting no errors.

For reference I'm using Unity 2019.1.6f1

**Comment by desplesda** [comment]
Hello! We've identified a bug on versions prior to 2019.2 - are you able to update your project to use that? (The next release will include support for 2018.4 LTS and above, but that hasn't landed in the `master` branch yet.)

**Comment by robbiesaurus** [comment]
Thanks for the quick response, unfortunately i'm pretty deep in a project at the moment and updating the project might be problematic. Do you have a workaround that I could use for the moment? If not I'll wait for the next release, thanks
