### ISSUE TITLE
add Yarn script to Unity's Project > Create menu

### ISSUE THREAD

**Issue by radiatoryang** [YarnSpinnerTool/YarnSpinner#214]
considering that VS Code is / will be a primary editor for some people, it would be good to let users make new .yarn scripts via a "Yarn Dialogue" option item in the Create menu of the Unity Project tab

and then I imagine it would initialize a new .yarn file based on a template somewhere in /YarnSpinner/ that the user can optionally edit

![image](https://user-images.githubusercontent.com/2285943/74685450-9c76c980-519c-11ea-814c-51b6bacb48fe.png)

not super critical, just a nice QoL workflow improvement to support the emerging VS Code stuff rolling out

**Comment by desplesda** [comment]
I like this idea a lot. Will add.

Note to self: [`UnityEditor.ProjectUtil.StartNameEditingIfProjectWindowExists`](https://github.com/Unity-Technologies/UnityCsReference/blob/d36e9af72e43f7575c58a5a9aeefa8133928fdb1/Editor/Mono/ProjectWindow/ProjectWindowUtil.cs#L523), which is undocumented but public, can be used to replicate the existing "create an asset and rename it" flow that other existing types provide.

**Comment by desplesda** [comment]
Done. Will ship in the next version!
