### ISSUE TITLE
DialogueRunner.cs onDialogueComplete callback

### ISSUE THREAD

**Issue by unknowndevice** [YarnSpinnerTool/YarnSpinner#215]
Add a callback function to DialogueRunner.cs to notify a user when dialogue has completed.

This was discussed in the slack channel but what I'd like to see is a callback function added to DialogueRunner.cs that can notify a user when dialogue has completed. This could be called in the function ```void HandleDialogueComplete```. DialogueUI.cs can also subscribe to this function.

The use case for something like this:

1) External script passes yarn files to runner and asks it to start
2) Runner passes lines to dialogue ui
3) Once finished the runner should let the external script know it can shut everything down.

In the above example right now the external script has two choices, constantly checking isDialogueRunning or subscribing to onDialogueEnd in DialogueUI.cs. Ideally the external script should not have to reference DialogueRunner.cs and DialogueUI.cs to function correctly. The external script shouldn't have to care about the UI.

**Comment by unknowndevice** [comment]
Here's an example solution that would allow an external script and the DialogueUI.cs to receive the callback. The bonus here is DialogueUI.cs can continue to avoid holding a reference to DialogueRunner.cs

```csharp
/// A Unity event that receives the name of the node that just
/// finished running
[SerializeField] StringUnityEvent onNodeComplete;
[HideInInspector] public UnityEngine.Events.UnityEvent onDialogueComplete;

...

Dialogue _dialogue;
public Dialogue dialogue {
    get {
        if (_dialogue == null) {
            // Create the main Dialogue runner, and pass our
            // variableStorage to it
            _dialogue = new Yarn.Dialogue(variableStorage);
            ...
            onDialogueComplete.AddListener(this.dialogueUI.DialogueComplete);
            ...
        }
        return _dialogue;
    }
}

void HandleDialogueComplete()
{
    isDialogueRunning = false;
    onDialogueComplete?.Invoke();
}
```

**Comment by desplesda** [comment]
This feature is present in v1.1, so I'll go ahead and close this issue now. Thank you!
