### ISSUE TITLE
[Feature Request] Commands/functions during lines

### ISSUE THREAD

**Issue by janmaslov** [YarnSpinnerTool/YarnSpinner#216]
Having hacked in a solution for running special commands defined separately from typical Yarn Spinner commands while a line is being revealed, I think it might provide a great deal more flexibility to be able to run the same set of Yarn Spinner commands _while_ a line is running.

Of course Yarn Spinner itself isn't concerned with lines being revealed over time and so on, as it only delivers the string to display and handles the commands. But as it _does_ handle calling of commands, I think it's not super unreasonable to expect commands being run at any given moment in the dialogue. If this is non-trivial (and it might be, given Yarn Spinner's linear nature and it being decoupled from any UI code), maybe Yarn Spinner could provide some data alongside the line of text as to which command is placed at which index in the current line, so that the game code could react to it.

**Comment by desplesda** [comment]
Just to make sure I'm thinking about the same thing you are, you're asking if it can be made possible to do this, right?

```
Character: Hey, good to see you-- *screen starts shaking* oh no, an earthquake!
```

And have the event happen during the delivery of the line?

**Comment by janmaslov** [comment]
Yes, exactly this.

**Comment by janmaslov** [comment]
\*facepalm\*
Of course it only now occurred to me that this could be fully handled on the UI code side by just having something in the Yarn scripts that marks lines that should be appended to the one already displayed.

So to take your example, it would be possible to do something like this without modifying any Yarn Spinner-related code:
```
Character: Hey, good to see you-- 
<<ScreenShakeIndefinitely 2.5>>
<<AppendNextLine>>
Character: oh no, an earthquake!
```
The custom `AppendNextLine` command would tell the UI to not replace the text currently displayed in the textbox.
Not the cleanest of solutions, but it would work and be way less clunky than the monstrosity I currently have in place. Having it integrated in Yarn Spinner directly would of course make such situations even cleaner.

**Comment by desplesda** [comment]
Something like this was done in Night in the Woods, where the game defined a command `runNextLinesTogether` which set a flag to append lines.

That said, the syntax in the post I made earlier is likely to make it into a future version of Yarn Spinner, as a side effect of our plans to add attributed strings (like boldface fonts or shaking letters.)

**Comment by janmaslov** [comment]
Fantastic. Well, then this is solved for me. :) Having a command like that will be enough for my use case.
