### ISSUE TITLE
DialogueUIBehavior should send a signal whenever the dialogue is stopped.

### ISSUE THREAD

**Issue by satanas** [YarnSpinnerTool/YarnSpinner#221]
Similar to `DialogueComplete`, `DialogueRunner` should notify the UI whenever a dialog has been stopped (via the `Stop()` method).

**Comment by desplesda** [comment]
Thanks for filing the issue!

Is it worth adding an additional method that conveys a very similar piece of information? What do you need to know about `Stop()`ped scripts that's different to when scripts come to an end on their own?

**Comment by desplesda** [comment]
Hi! There hasn't been any more activity on this issue, so I'll go ahead and close it now. Please file a new one if you want to re-open this conversation!
