### ISSUE TITLE
(QUESTION) How can I use variables in dialogs to modify other scripts?

### ISSUE THREAD

**Issue by chevidal45** [YarnSpinnerTool/YarnSpinner#233]
I dont know if this is the best way to ask a question but I have a doubt. First of all I'm doing a videogame based on decision with yarn spinner. 

My problem is that I dont know how to change things on the game because of the decision you took. I mean, I dont know if I can use variables in dialogs and if I can use these variables to modify antoher script or something like that. I think I have to do something with the script InMemoryVariableStorage but I dont know how.

**Comment by unknowndevice** [comment]
Hi! What you're looking for is commands. Please read the documentation and look at the example project of how to use them before making an issue on Github https://yarnspinner.dev/docs/unity/working-with-commands/

This isn't a bug.

**Comment by desplesda** [comment]
Yep! As @unknowndevice said, the easiest way to make things happen in the game during dialogue is with commands. I'll close this issue now - if you have more questions on how to use Yarn Spinner, I'd suggest checking out our Slack community at https://lab.to/narrativegamedev. 

Thanks for using Yarn Spinner!
