### ISSUE TITLE
if multiple blocking commands are placed in a row, execution stops

### ISSUE THREAD

**Issue by jamesoppman** [YarnSpinnerTool/YarnSpinner#234]
eg:

<<MovePlayer Left 1>>
<<MovePlayer down 2>> 
<<MovePlayer Left 3>> 
<<MovePlayer down 1>> 

If I place more than 1 blocking command, only the first and second command is run. Oncomplete fires correctly after each move. If put some dialogue between each command, everything executes fine.

**Comment by unknowndevice** [comment]
can you show the code for your MovePlayer command?

**Comment by desplesda** [comment]
Hi @jamesoppman! Following up on this 😄

**Comment by desplesda** [comment]
There hasn't been any further activity on this thread, so I'm closing it now. @jamesoppman, if you're still experiencing this, please post here and I'll re-open this issue!
