### ISSUE TITLE
Expressions placed at the start of a line are not added to substitutions

### ISSUE THREAD

**Issue by francisptr** [YarnSpinnerTool/YarnSpinner#243]
**What is the current behavior?**

When a line starts with an expression, such as: 
_{$favouriteFood} is great!_

The resulting Line contains no substitutions, and the resulting formatted line in-game remains: 
_{$favouriteFood} is great!_

If you add a single character at the start of the line, for example: 
_a{$favouriteFood} is great!_

The resulting formatted line contains the substitution, such as: 
_aCheese is great!_

**What is the expected behavior?**
Expressions placed at the start of a line should be substituted.

**Please tell us about your environment:**
  - Yarn Spinner Version: YarnSpinner 1.1.0

**Comment by desplesda** [comment]
Will be fixed in the next release!
