### ISSUE TITLE
Is there any standalone lines tagging binary or script ? 

### ISSUE THREAD

**Issue by ashlander** [YarnSpinnerTool/YarnSpinner#245]
Hi All,

As I understand YS is highly integrated with unity, and lines tagging for localization is triggered within some unity UI tool/plugin (I am not familiar with it, so I may name it all wrong). But is there some script triggered, which may be used locally (or in e.g. CI/CD) to make lines tagging ?

**Comment by McJones** [comment]
Currently not, no.
We used to have YarnSpinnerConsole which was a standalone command line tool which had support for those kinds of tasks but it slipped behind development of the Unity plugin and no longer works (issue #175 and the linked issues there documents a lot of this).
We do still want it to work and hopefully have it running for the v2 release.

Thanks for reminding us of this, we once again have let this slip out of our roadmap and we can't keep doing that.

I am closing this issue, if you want to discuss it and any features you'd like it to have please go to issue #175 and comment there so we can keep all discussion in one place.
