### ISSUE TITLE
Unity integration has moved to a new repo

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnSpinner#249]
Hello!

As discussed in https://github.com/YarnSpinnerTool/YarnSpinner/issues/246, we've split the Unity integration into a new repository. If you're looking for the Unity code, please head there!

**Comment by McJones** [comment]
Just to save people a few clicks, the Unity repo is here: https://github.com/YarnSpinnerTool/YarnSpinner-Unity for those who are curious.
