### ISSUE TITLE
Inconsistent syntax for command, method, functions....

### ISSUE THREAD

**Issue by WeslomPo** [YarnSpinnerTool/YarnSpinner#256]
I write a couple of dialogs, and found that YS have very inconsistent syntax for commands and functions.

First of all, I rewrite Unity side for clearer interfaces, and build my own version of dialogue drawer that utillize power of DI.

And I found that Yarn Spinner have 4 different kind of handlers. And they differentiate to 2 type - one get `string[]`, other get `Value[]` (and both have two version that return something or not). So, there are problem lies.

To execute string[] methods, you call that like `<<Something Some.Argument 32>>`, but other you need to write like `<<if ValueSomething("Some.Argument", 32)>>` to work with. It is really annoying, because you need to know how to call your function and where you called it. Also, if you write `<<Something "Some.Argument" 32>>` - it will work - not syntax error, you know that you have problem if you DB can't found `""Some.Argument""`, and you will be lucky if you put not found argument in brackets beforehand, because `"Some.Argument" was not found` looks legit.
It work even when you call it like `<<Something("Some.Argument",32)>>` - but this will try find method with name `Something("Some.Argument",32)`.

So, I think here we need remove string[] version. Because it inconsistent and Value[] have better argument syntax error handling.

**Comment by McJones** [comment]
Since this was opened there have been multiple changes to how commands and functions work.
Overall we still like the distinction between the two so I think I am going to close this.
Thanks for opening it.
