### ISSUE TITLE
empty comment gets tagged for localization.

### ISSUE THREAD

**Issue by naNuke** [YarnSpinnerTool/YarnSpinner#258]
**What is the current behavior?**

Having an empty comment line `// ` without any text
tags the empty lines for localization as such: `// #line:092a51a`

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

Stumbled upon this issue by using comments for formatting, example:
```
// -------------------------------------------------------------------------
// This section happens only if character has been spoken to before
// -------------------------------------------------------------------------
// 
```

The produced yarn code after adding localization lines:
```
// -------------------------------------------------------------------------
// This section happens only if character has been spoken to before
// -------------------------------------------------------------------------
// #line:092a51a
```

**What is the expected behavior?**

Comments should probably be completely ignored for localization purposes

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 1.2.0
  - Unity Version: 2019.4.0f1

**Comment by desplesda** [comment]
I've also spotted this incorrect behaviour in the following situation:

```code
Anne: That's ok! This will all go away in a moment. // reassuring 
Tom: What?!  // surprised, confused 
```

In this situation, the line tagger will incorrectly add line tags at the end of the line, inside the comment; it should instead be placed before the comment.

```code
Anne: That's ok! This will all go away in a moment. // reassuring #line:a1b2c3
Tom: What?!  // surprised, confused #line:d4e5f6
```
