### ISSUE TITLE
How to use protobuf.net instead of google protobuf

### ISSUE THREAD

**Issue by zhepama** [YarnSpinnerTool/YarnSpinner#263]
**Because my project uses protobuf.net,**

**I don't want to reference Google.protobuf.**

**what should I do?**

**Comment by desplesda** [comment]
Unfortunately, because of the way that the way that protobuf-loaded classes from Google.Protobuf are derived from a class in that assembly, it's not possible to remove the dependency without rearchitecting those classes.

**Comment by desplesda** [comment]
Closing this issue, because I don't think that we have a solution for you that doesn't mean significantly re-engineering large parts of Yarn Spinner. Apologies!
