### ISSUE TITLE
MLAgents Support

### ISSUE THREAD

**Issue by bmootedki** [YarnSpinnerTool/YarnSpinner#272]
Hello,

This is not a bug, but more of a request.

Can we get a YarnSpinner that is compiled with google.protobuf V3.9.1.0 instead of V3.10

I am unable to use MLAgents package with Yarn currently and it is causing me quite a struggle, i have tried hiding the yarn package in another ILMerge but to no avail when actually building a version.

I'm sure this would benefit quite a few others as machine learning becomes more and more popular.

Thanks!

**Comment by bmootedki** [comment]
i managed to download an older version of the dll and downgrade / rebuild myself then import to unity with package manager from disk.

**Comment by lukebandy** [comment]
Hey @bmootedki, is there any chance that you could write up some rough steps on solving this?

**Comment by bmootedki** [comment]
Hey @lukebandy   If I recall it went something like this

1. Download whichever version of yarn from git (as code)
2. Open the project in VS
3. replace the .dll with the version you want to use
4. change the package json info's name or version
5. import to unity as a local package after removing the other Yarn you have
