### ISSUE TITLE
In line commands do not seem to be working. 

### ISSUE THREAD

**Issue by ryanhaight444** [YarnSpinnerTool/YarnSpinner#278]
Here is my line of yarn code:
`Woah I didn't notice you were a dog <<wait 1>> cool.`

When I try to compile this in Unity I get the following error message: 
`Error on line 14 at position 40:
mismatched input 'w' expecting COMMAND_IF
Woah I didn't notice you were a dog <<wait 1>> cool.
`
I can get rid of the error message if I move the command to a newline however this then splits the dialogue into two lines which I want to avoid. 
  
  - Yarn Spinner Version: 1.2
  - Unity Version: 2019.3.6f1

Maybe inline commands like this are not intended, I am not sure. If they are not intended, do you have any suggestions on how to go about implementing an inline wait command, with attributes or format expressions?

Thanks for your time and consideration!
Ryan

**Comment by McJones** [comment]
Commands are not designed to be embedded in-line like this.
Like you worked out commands need to go on their own line.
