### ISSUE TITLE
ArgumentOutOfRangeException Error When Adding Options!

### ISSUE THREAD

**Issue by SethDharma** [YarnSpinnerTool/YarnSpinner#279]
Everything was working fine until recently when it started to throw this error when trying to select an option. I only have 2 option buttons. 

My Yarn file is structured like this:
**I don't think that's a good idea.
 [[Leave|Leave]]
 [[Stay|Stay]]**

Which then branch off into other nodes. But, it throws that argument out of range error. It was working, now its not and i cant seem to find the source of the problem.

ERRORS:
**ArgumentOutOfRangeException: Specified argument was out of the range of valid values:
DialogueException: Cannot continue running dialogue. Still waiting on option selection.**

**Comment by SamGrant98** [comment]
Was their a solution to this problem? I am currently facing this issue.
