### ISSUE TITLE
Node titles can't start with a number

### ISSUE THREAD

**Issue by StefanJanssen95** [YarnSpinnerTool/YarnSpinner#280]
**What is the current behavior?**
I've created a single node with as name "1stLine" which according to the documentation should be allowed but throws an error because the title starts with a '1'. The '1' can be in any position of the node title but the first.

> The name of the node, in this case nodename, needs to be unique across the entire project, and can be any combination of upper or lower case letters and numbers. Node titles can’t have spaces.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
Create a node with a title starting with a number, after importing it in Unity the parser will throw an error.

**What is the expected behavior?**
The title should be able to start with a number or the documentation should be updated.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 1.2.6 (downloaded from the unity repo)
  - Unity Version: 2020.0a18.2359

**Comment by TheMartianLife** [comment]
Though node names can include numbers and underscores, they should begin with a letter. Docs will be updated to reflect this, to prevent confusion in the future (see [pull request here](https://github.com/YarnSpinnerTool/Docs/pull/13)).

With this constraint in mind, your node could still be named `Line1st`, `Line_1st`, `FirstLine` or similar.

Thanks for bringing this to our attention!
