### ISSUE TITLE
comparing null to any string evaluates to true

### ISSUE THREAD

**Issue by luvcraft** [YarnSpinnerTool/YarnSpinner#282]
(bug copied from YarnSpinner-Unity because it's not a Unity-specific problem)

**What is the current behavior?**
In yarn script, comparing a null value to a string evaluates to true.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
example script:
<< if null is "foo" >>
    null is foo!
    this dialog should not be shown, but it is
<< else >> 
    this dialog should be shown, because a null variable does not equal "foo"
<< endif >> 

however, comparing with the string first DOES evaluate correctly, e.g.:

<< if "bar" is null >>
	bar is null!
<< endif >>

This is ESPECIALLY problematic when comparing a null variable to a string; for example:

<< if $unassignedVariable is "very important key" >>

will evaluate to TRUE if $unassignedVariable is NULL.

**What is the expected behavior?**
comparing a null value to a string should always evaluate to false, except maybe for an empty string

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 1.2.7 (latest from package manager)
  - Unity Version: 2019.4.9

**Other information** 
see above example

**Comment by melancholie** [comment]
I would like to second this bug. We had some really odd behaviour that we were able to trace back to this bug. I hope this can be fixed soon. It definitely not intuitive to have to make empty variables to make sure they won't be checked before being set for the first time.

**Comment by desplesda** [comment]
This behaviour no longer appears in the `develop` branch, due to the implementation of the new type system. As a result, I'll close this now. Thanks for the bug report!
