### ISSUE TITLE
My lines of dialogue are skipping ahead! Has anyone else experienced this issue?

### ISSUE THREAD

**Issue by AgnesEkblom** [YarnSpinnerTool/YarnSpinner#284]
Hi!

So I'm using yarnspinner for a game I'm making in unity. Basically, everything runs smoothly except when i have one node that should interupt the one running, if a button is pressed. for some reason, this node will flick through the lines at a random, faster speed than i've asked it to. In this project, every node is matched up as subtitles to an audio file, and i've used the "<< wait x >>" command to make sure every line is up for the right amount of time. I start the node by writing "DialogueRunner.StartDialogue("MirjamShortExplanation");", as with other lines of code previously in the project, and this is the only one that won't work. Please, if you have any ide what might be causing this, i'd love to hear it. 

Thank you so much!

**Comment by desplesda** [comment]
Hi! Are you using Yarn Spinner 1.2 (the most recent mainline release), or the Yarn Spinner 2 beta?

Additionally, are you seeing this behaviour in the Space demo scene?

Finally, are you using the built-in DialogueUI, or are you using your own (or a customised DialogueUI)?

**Comment by AgnesEkblom** [comment]
@desplesda I'm using version 1.2.7, which i have downloaded in my package manager :) I'd have to rewrite the code of the space demo quite a lot to check, since it only happens when i interrupt a node with another node, also the space scene does not use the wait x command between lines to match with a voice over, and by then im not sure the comparison would help? if you think it would i can probably fix it though, just let me know :) I am using the built in dialogue ui, i havent changed anything in the scripts provided (Dialogue ui, dialogue runner or variable storage) to my knowledge! Thank you

**Comment by desplesda** [comment]
This issue now, I believe, fixed in the most recent beta. I'm going to close this issue here, but if you're still seeing it in 2.0, please re-open!
