### ISSUE TITLE
Single character shortcut options fail on import

### ISSUE THREAD

**Issue by randalfien** [YarnSpinnerTool/YarnSpinner#289]
Using a single character shortcut option fail the import:
Does not work:
```
Anezka: Hi?
-> ?
Nela: what?
```
Does work
```
Anezka: Hi?
-> ??
Nela: what?
```

**Comment by desplesda** [comment]
This appears to have been fixed in 8c014bef9b8a769. If you're still seeing this issue, please let me know!
