### ISSUE TITLE
Upgrader doesn't upgrade v2 <<jump>> commands

### ISSUE THREAD

**Issue by radiatoryang** [YarnSpinnerTool/YarnSpinner#290]
**What is the current behavior?**

Given the Yarn script with outdated v1.x syntax:

```
title: NeedsAnUpgrade
---
Hello! Let's trying going to anotherNode with the old way!
[[anotherNode]]
===

title: anotherNode
---
Hey now you're in another node!
===
```

The upgrader in the Unity editor window doesn't upgrade the jump command to the new v2 equivalent `<<jump anotherNode>>`, and I get "No upgrades required for (this file)" in the Console.

Although I'm catching the error in Unity, this seems to be an issue with LanguageUpgrader stuff in the YarnSpinner.dll

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

I'm able to reproduce off of the current YarnSpinner-Unity develop branch with the above script, so if this is fixed already then maybe we need to update the DLL in the Unity repo

**What is the expected behavior?**

The Upgrader needs to detect and upgrade old v1 `[[NodeName]]` and `[[Label|NodeName]]` jump commands

**Please tell us about your environment:**
  
  - Yarn Spinner Version: v2.0.0-beta2 (develop)
  - Unity Version: 2020.1.17f1

**Other information** 

Also running the old style jump command results in this exception: `ArgumentException: Expected an identifier inside markup in line "[[anotherNode]]"` ... But ideally you probably want to catch this specifically as a v1 syntax problem, and warn the user to upgrade their Yarn script. Maybe just check if the line contains a "[[" even though it shouldn't?

Here's my stack trace for that exception (from Unity, sorry):
```
Yarn.Markup.LineParser.ParseID () (at <19750b85f5444d9f99effdeecf4acace>:0)
Yarn.Markup.LineParser.ParseAttributeMarker () (at <19750b85f5444d9f99effdeecf4acace>:0)
Yarn.Markup.LineParser.ParseMarkup (System.String input) (at <19750b85f5444d9f99effdeecf4acace>:0)
Yarn.Dialogue.ParseMarkup (System.String line) (at <19750b85f5444d9f99effdeecf4acace>:0)
Yarn.Unity.DialogueRunner.<CreateDialogueInstance>g__HandleLine|70_5 (Yarn.Line line) (at Assets/YarnSpinner-Unity/Runtime/DialogueRunner.cs:781)
```

**Comment by desplesda** [comment]
Fixed as of cb753e83985627e4a2e7a82380fffcd4c85d7df4. Thank you!
