### ISSUE TITLE
Proposal: Arbitrary line metadata

### ISSUE THREAD

**Issue by xsduan** [YarnSpinnerTool/YarnSpinner#296]
This is a bit of a weird ask and it's not STRICTLY necessary, but...

## Introduction

Right now, I am making a sort of "environmental" dialogue (no interaction needed, etc). Part of the mechanics I want is allowing overlapping dialogues, which I am accomplishing by simply queueing up lines for a duration rather than waiting for the previous line to finish so I don't need to allocate more dialogue runners if I don't actually care about the sequence of the dialogue. Additionally, I want to be able to randomly pop up dialogue without having to define all 2<sup>n</sup> permutations of characters, so I want to define some way to make the dialogue choose characters in the backend. These, while super simple to implement, both require more metadata than what's able to be provided.

## Rationale

It would be nice to have access to metadata without having to parse the name string (ew). Right now this is how I'm doing it:

```
title: test
tags:
---
// within the character `_mplx_groupa`, show the popup bubble for 1 second before automatically closing
-> _mplx_groupa|1: Yeah, so I asked if I could get it in a day late. #line:0000001
-> _mplx_groupa|1: Isn't that something! #line:0000002
-> _mplx_groupa|1: Sorry, I have to work late. Deadline's coming up. #line:0000003
-> _mplx_groupb|1: For real? #line:0000004
-> _mplx_groupb|1: That's too bad. #line:0000005
-> _mplx_groupb|1: I never knew that! #line:0000006

<<wait 1>>
<<jump test>>
===
```

This would allow some hooks for behavior/validation (completely custom implementations so nothing that YarnSpinner needs to care about, but just an idea of my use cases):

```
title: test
tags:
---
// validates that the character is a character multiplex group, not an actual static character
// but skips this line if defined character not set
-> _mplx_groupa: Yeah, so I asked if I could get it in a day late. #line:0000001#duration:1#mux:default
// picks random character out of group
-> _mplx_groupa: Isn't that something! #line:0000002#duration:1#mux:random 
// fails loudly if character is not set for group
-> _mplx_groupa: Sorry, I have to work late. Deadline's coming up. #line:0000003#duration:1#mux:last 
// finds closest character to player
-> _mplx_groupb: For real? #line:0000004#duration:1#mux:closest 
// emotions!
-> _mplx_groupb: That's too bad. #line:0000005#duration:1#mux:random#emotion:sad 
    _mplx_groupb: I hope you find what you were looking for. #line:0000007#mux:last
// etc etc
-> _mplx_groupb: I never knew that! #line:0000006#duration:1#mux:random

<<wait 1>>
<<jump test>>
===
```

It's also just kind of weird that the #line syntax is randomly used for that and only that (especially since YarnSpinner tries to make code-related features mostly neutral to implementation elsewhere), so it makes sense to put it in there.

## Proposed solution

As above, it would be nice if we could have some custom line tags like so:

```
title: test
tags:
---
-> _mplx_groupa: Yeah, so I asked if I could get it in a day late. #line:0000001#duration:1
-> _mplx_groupa: Isn't that something! #line:0000002#duration:1
-> _mplx_groupa: Sorry, I have to work late. Deadline's coming up. #line:0000003#duration:1
-> _mplx_groupb: For real? #line:0000004#duration:1
-> _mplx_groupb: That's too bad. #line:0000005#duration:1
-> _mplx_groupb: I never knew that! #line:0000006#duration:1

<<wait 1>>
<<jump test>>
===
```

## Detailed design

On the API side, it would look something like this:

```cs
public override void RunLine(LocalizedLine dialogueLine, Action onDialogueLineFinished) {
    var _ = dialogueLine.Props["mux"] // readonly Dictionary<string, string>
    // maybe?
    dialogueLine.Props["duration"].TryGetFloat(out float _, nullValue: -1); // readonly Dictionary<string, YarnValue> or something
    // and of course the standard TryGet stuff
    dialogueLine.Props.TryGet("mux", out string _);
    dialogueLine.Props.TryGetString("mux", out string _); // maybe?
    dialogueLine.Props.TryGetEnum("mux", out MultiplexType _); // bool TryGetEnum<TEnum>(string, out TEnum), and other overloads
    dialogueLine.Props.TryGetFloat("duration", out float _);

    onDialogueLineFinished();
}
```

### Bikeshedding

I'm unsure if `#k1:v1#k2:v2` or `#k1:v1,k2:v2` or something would be better but I don't really care about the specifics, so whatever's easiest for the parser I suppose.

## Backwards Compatibility

It would be 100% backwards compatible since `line:` would simply become a key in the syntax and YarnSpinner would just parse it out when doing i18n.

## Alternatives considered

Evidently it isn't a dealbreaker not to have it, since I have already gone ahead and done it with the character names and custom parsing, and it is veering heavily into the territory of "accidentally programming language"...but it would be nice to have. I'm not really concerned with this specifically getting into the spec provided I have zero idea of what your design goals are, but it would make my life a whole lot easier if we had a property grab-bag on each line.

## Acknowledgments

my 3am fever dream brain. I don't doubt there's a lot better way I could do something like this but I couldn't think of it, and I wanted to utilize the YarnSpinner i18n framework so I won't have to make the translators learn 3 different types of translation software when it comes time for that.

**Comment by desplesda** [comment]
I like this idea, and the grammar currently already allows for an arbitrary number of hashtags at the end of a line (we just don't do anything with them except for `line:` tags).

For example, the following Yarn will compile just fine right now:

```
Me: Here's a line #line:0001 #duration:2
```

The only difference, if I'm reading your proposal correctly, is that we'd provide a mechanism for accessing the `duration` tag. Let me know if I have that wrong!

One other thing to consider is that information that controls how a line is displayed might be better served through markup. For example:

```
Me: [duration=1]Here's a line[/duration] #line:0001
```

**Comment by xsduan** [comment]
> The only difference, if I'm reading your proposal correctly, is that we'd provide a mechanism for accessing the duration tag. Let me know if I have that wrong!

yep that’s right. 

> One other thing to consider is that information that controls how a line is displayed might be better served through markup. For example:

I think that would work yes, but part of the issue is that the duration is for the entire bubble (it just shows up) so there isn’t really a reasonable way to have it only show up for part of the bubble. I’m unsure if you can have self contained tags along the lines of `<br>` though even in that case the location of the tag itself implies semantics that don’t actually exist. 

However I genuinely had not thought of that so maybe I’ll look into it instead of the name parsing in the meantime.

**Comment by desplesda** [comment]
> I think that would work yes, but part of the issue is that the duration is for the entire bubble (it just shows up) so there isn’t really a meaningful way to have it only show up for part of the bubble.

That makes sense. What you're describing is something that affects the entire line, not regions of it.

>  I’m unsure if you can have self contained tags along the lines of <br> though even in that case the location of the tag itself implies semantics that don’t actually exist.

Self-contained tags like `[br/]` are definitely supported in the grammar, though there's no existing logic for controlling any specific tags (aside from `[character]`, which is already a special case.)

**Comment by Haapavuo** [comment]
For Options phase duration, I created a command: `<<deadline 1.5 Return.Node.Name>>` where 1.5 is the duration the player has to answer and Return.Node.Name is the node where YarnSpinner will jump if the deadline is reached.

**Comment by McJones** [comment]
This was added as part of https://github.com/YarnSpinnerTool/YarnSpinner-Unity/pull/146, closing this as done.
Thanks to everyone involved
