### ISSUE TITLE
How to cancel current node?

### ISSUE THREAD

**Issue by satanas** [YarnSpinnerTool/YarnSpinner#297]
Hi team, first of all, thanks again for putting this tool together. I have the following use case:

I start a node (let's say "nodeA") and per each line of that node I wait 4 seconds before returning the `ContinueExecution` (this is to automatically advance through the node but giving the players enough time to read the text).

The problem is that, at some point, I'd like to interrupt the current node and jump into another one (let's say "nodeB"). Right now, I'm just stopping all coroutines that wait and running `dialogueRunner.StartDialogue("nodeB");` but I wanted to confirm with you if I need to do something else to avoid things like memory leaks and leave everything in a clean state.

Thanks for the help!

**Comment by desplesda** [comment]
No, there's no cleanup you need to do if you interrupt a node and go somewhere else. Every time you start a node with `StartDialogue`, the internal state is reset.

**Comment by satanas** [comment]
Awesome, thanks for the clarification.
