### ISSUE TITLE
Markup cannot be escaped

### ISSUE THREAD

**Issue by McJones** [YarnSpinnerTool/YarnSpinner#304]
**What is the current behavior?**

Currently there is no easy way to escape markup in a line, so if for example you want to show the text `[hand over item]` this will be assumed by the dialogue runner to be a malformed line of markup.
We want an easy means of preventing the text as being assumed to be markup.
The escaping exists for this reason but we can’t escape the markup delimiters, so `\[hand over item\]` doesn’t work, the line will be delivered literally.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

- Add the following text to your yarn `[hand over item]`
- See it gets declared invalid markup
- rewrite line as `\[hand over item\]`
- See line doesn’t get delivered as `[hand over item]`.

**What is the expected behavior?**

Line will allow escaping of the markup characters.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.0 beta 4
  - Unity Version: 2020.3.16f1

**Other information** 

For now a workaround will be to use the `nomarkup` markup to prevent it being seen as markup, so by typing `[nomarkup][hand over item][/nomarkup]` it will send over the line as `[hand over item]` as expected but this is a lot of typing.

**Comment by desplesda** [comment]
Fixed in 1fe282627691383d629785bbe834d104e61941b5. Thank you!
