### ISSUE TITLE
2.1 Dialogue options obscured after <<jump>> if intermediate line is added

### ISSUE THREAD

**Issue by MiguelValSus** [YarnSpinnerTool/YarnSpinner#315]
We are setting up some simple and straight-forward conversation that includes simple dialogue options that trigger different outcomes. However, when using a specific structure the Options List View only displays the first dialogue option, and not the rest. Here's the Yarn Script setup:

`Blue: Welcome, Red. #line:0972d1f `
`Blue: How are you feeling today? #line:0d26e27 `

`-> Red: Not quite happy, to be honest. #line:06dddee`
`     Blue: C'mon, cheer up. #line:07be2d0 `
`    <<jump CheerUp>>`
`-> Red: Feeling great! Let's go on that adventure. #line:0d3096f `
`	Blue: Yeah! #line:0b66e5c `
`    <<jump Finish>>`
`===`

`title:CheerUp`
`--- `
`Blue: Is there anything I can do about it? #line:05e5207 `
`Red: Not really. #line:01a112f `
`<<jump Finish>>`
`===`

`title:Finish`
`---`
`Red: Let's just go. #line:0990f6b `
`===`

With that, only the first 'Red' line (06dddee) is shown in the options while 0d3096f is omitted, and then it jumps to the **CheerUp** block. However, there is a way in which the dialogue options display works as intended, and that is by just moving the 07be2d0 line to inside the **CheerUp** block, like this:

`-> Red: Not quite happy, to be honest. #line:06dddee`
`    <<jump CheerUp>>`
`-> Red: Feeling great! Let's go on that adventure. #line:0d3096f `
`	Blue: Yeah! #line:0b66e5c `
`    <<jump Finish>>`
`===`

`title:CheerUp`
`--- `
`Blue: C'mon, cheer up. #line:07be2d0 `
`Blue: Is there anything I can do about it? #line:05e5207 `
`Red: Not really. #line:01a112f `
`<<jump Finish>>`
`===`

With that structure, the Options List View correctly displays all dialogue options and correctly launches the 'Blue' 0b66e5c response after selecting the second option and before moving to **Finish**.

Is there something we are doing incorrectly? Including a _jump_ action for each dialogue option seems the way to go, but maybe we shouldn't put intermediate lines like 0b66e5c in between the -> and the _jump_ to prevent this error?

  

  - Yarn Spinner Version: 2.1.0
  - Unity Version: 2022.1.0b8

**Comment by desplesda** [comment]
This is actually a problem with your syntax!

The way you've written it, Yarn Spinner is seeing a single option ("Red: Not quite happy, to be honest."), and then on the next line, no indentation before "Blue: C'mon, cheer up.". Yarn Spinner therefore interprets this as a solitary choice with no lines within it, followed by the line "Blue: C'mon, cheer up.".

If you want lines to belong to an option, indent them:

```
Blue: Welcome, Red. #line:0972d1f 
Blue: How are you feeling today? #line:0d26e27

-> Red: Not quite happy, to be honest. #line:06dddee
    Blue: C'mon, cheer up. #line:07be2d0
    <<jump CheerUp>>
-> Red: Feeling great! Let's go on that adventure. #line:0d3096f 
    Blue: Yeah! #line:0b66e5c 
    <<jump Finish>>
```

For more information, see the [documentation on options](https://docs.yarnspinner.dev/getting-started/writing-in-yarn/lines-nodes-and-options#options).

I'll close this issue here; please re-open this issue if I've misunderstood your problem!

**Comment by MiguelValSus** [comment]
Ah, sorry about that! They are actually indented in my current code, yeah, this was just an issue of GitHub's auto formatting. This is how it looks like in the actual Visual Studio Code file:

![image](https://user-images.githubusercontent.com/79455131/154859721-53c8af5c-021f-4cd5-a27c-be2de4c36151.png)

Maybe I'm doing the indenting wrong? I'm just basically pressing 'Tab' for it. In any case, the problem still persists.

**Comment by MiguelValSus** [comment]
Okay, I basically re-did the code snippet and, somehow, it works now. Guess I maybe screwed up with the original indentation.

Sorry and thank you!
