### ISSUE TITLE
Expired certificate for website

### ISSUE THREAD

**Issue by dalbitresb12** [YarnSpinnerTool/YarnSpinner#322]
Hi! I just discovered this project and it looks really good. 

I noticed that the SSL certificate for [yarnspinner.dev](https://yarnspinner.dev/) is expired and since you have HSTS enabled, the website can't be accessed (and the warning can't be ignored). So this is just a friendly ping to remind you to renew the certificate :)

![image](https://user-images.githubusercontent.com/7624090/169687844-ea325e0b-5f88-4dd8-bac9-69d7f0be8963.png)

**Comment by desplesda** [comment]
This is now fixed! Thanks for the alert!
