### ISSUE TITLE
Empty lines inside an indent trigger compile warnings

### ISSUE THREAD

**Issue by fmoo** [YarnSpinnerTool/YarnSpinner#326]
**What is the current behavior?**

When attempting to space out my script a bit with empty lines, I get a compiler error from yarn:

![image](https://user-images.githubusercontent.com/143504/183313929-4adb30df-1047-4d2d-9ea2-57e3d825e84c.png)

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

Have a script with something like:
```
<<declare $foo = true>>
<<declare $bar = true>>
<<if $foo == true>>
  <<if $bar == true>>
    Here is a line

    Here is another line
    <<set $foo = false>>
  <<endif>>
<<endif>>
```

**What is the expected behavior?**

We should be able to have blank newlines without whitespace inside of nested iffs

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.2.1-pre
  - Unity Version: 2019.4.36f1

**Other information**

**Comment by McJones** [comment]
This is related to YarnSpinnerTool/YarnSpinner-Unity#215.
Looking into this.
