### ISSUE TITLE
#lastline specialtag is not appearing

### ISSUE THREAD

**Issue by TheCell** [YarnSpinnerTool/YarnSpinner#330]
With the new minor version, we got the `#lastline` special tag. I wanted to use it in my project and found a bug where the tag is not set.

**What is the current behavior?**

The `#lastline` tag is not appearing.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

1. Create a new Unity Project and follow the installation instructions [installation-and-setup](https://docs.yarnspinner.dev/using-yarnspinner-with-unity/installation-and-setup)
2.  Setup the minimal dialog from the [quickstart](https://docs.yarnspinner.dev/using-yarnspinner-with-unity/quick-start)
3. Indent the Options:
```
title: Start
---
Wow! #testtag #line:0081ef0 
My first ever Yarn script in Unity! #line:0797281 

    -> Gosh! #line:0e722d5 
    -> Incredible! #line:019c6b4 
    -> I'm amazed! #line:0279430 

Anyway, time to get writing! #line:0ca3bce 
===
```

**What is the expected behavior?**

With indented options, the `#lastline` tag is not set. Removing the indention and running the dialog will correctly show the tag. I expected to get the tag even with an indention.
Edit: Same goes for commands and logic. If the last line is followed by an `<<if ...>>` or a custom command, the `#lastline` tag is not added.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.2.1
  - Unity Version: 2020.3.22f1

**Other information** 

To check the Metadata, browse the Plugin Folder and search for LineView.cs. You can add the following code at the opening of the method `RunLineInternal`:
```
var metadata = dialogueLine.Metadata;
if (metadata != null)
{
    Debug.Log(string.Join(",", metadata));
}
```

**Comment by McJones** [comment]
Not having a `#lastline` tag before if statements or commands is by design, we can't know the interactions of what happens after that point. You can add the `#lastline` tag yourself manually in these situations.
However not having a `#lastline` before the indented options though is unexpected and we're looking into it.
