### ISSUE TITLE
Language Server Completion hangs, breaks after many inline options for the remainder of the file

### ISSUE THREAD

**Issue by fmoo** [YarnSpinnerTool/YarnSpinner#349]
**What is the current behavior?**

When working in vscode on a file with a node with a large number of `->` inline options (e.g., more than 13), attempting to invoke the custom command completion anywhere after the branch hangs with "Loading...".  The more options, the longer the hang (and recovery time of the LSP).

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

Create a node with 13+ -> options and lines of dialogue below each.

Attempt to invoke custom command completion via typing e.g., `<<p` and pressing ctrl+space after the 13th line of dialogue (indented)  or even try to create a whole new node and use it.   The call will either never finish or take forever and return no results after many seconds.

![image](https://user-images.githubusercontent.com/143504/200955253-35f52474-3dc3-4db1-a21e-a7e67c2e11ef.png)
![image](https://user-images.githubusercontent.com/143504/200955296-8241dcb4-ee0f-4f44-8081-a23392574b9a.png)
![image](https://user-images.githubusercontent.com/143504/200955361-10a75468-79cc-4635-9f60-df12f63d952f.png)

Inserting a new node between Bug1 and Bug2 and attempting to use code completion in there works just fine;
![image](https://user-images.githubusercontent.com/143504/200956029-81ca6292-57e5-4a8b-931f-7ed8fb2336ab.png)

**What is the expected behavior?**

Would expect the typeahead to suggest `<<wait>>` or `<<if>>` or `<<stop>>` etc.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.2.2
  - Unity Version: 2021.3.12f1

**Other information** 

Here's a copy of my assets folder with the bug (title: Bug2):
[Assets.zip](https://github.com/YarnSpinnerTool/YarnSpinner/files/9975573/Assets.zip)

**Comment by McJones** [comment]
I definitely know where the LSP lives in the repos...
