### ISSUE TITLE
Trailing whitespace in ``title:`` leads to compiler error without information

### ISSUE THREAD

**Issue by julhe** [YarnSpinnerTool/YarnSpinner#350]
**What is the current behavior?**

If the title of a node has trailing whitespace, the compiler will give an error. There is no futher information on where or even what went wrong. This made finding the error really hard.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

Create a new yarn file with the following content:
```
title: ThisTitleHasTrailingWhiteSpace 
---
===
```

1. Try to run this file in VSCode (Ctrl + Shift + P -> Yarn Spinner: Preview Dialogue)
2. You should get the following message: 
![grafik](https://user-images.githubusercontent.com/18037091/216764202-15c7272b-f873-45bd-9a96-9cae9ee3e7fd.png)

**What is the expected behavior?**

Either an error marked by the extension or a more expressive error message.

**Please tell us about your environment:**
  

  - VSCode extension: last version from 2/3/2023, 21:56:26
  - Yarn Spinner Version: N/A
  - Unity Version: N/A

**Other information** 
N/A

**Comment by McJones** [comment]
Fixed in [c3daf30](https://github.com/YarnSpinnerTool/YarnSpinner/commit/c3daf30d2baeea3e1dd4a3f2f48f7fc45c4771f8), the next update of Yarn Spinner will include this fix.
Thanks for the issue, it was an interesting one to encounter.
