### ISSUE TITLE
.ysls.json no longer read in VS Code with extension v2.2.119

### ISSUE THREAD

**Issue by benwest** [YarnSpinnerTool/YarnSpinner#370]
After updating the Yarn Spinner VS Code extension to version 2.2.119, all my functions and commands in scripts cannot find their definitions from .ysls.json (no Unity). Reverting to 2.2.106 brings them back.

The [release notes](https://github.com/YarnSpinnerTool/YarnSpinner/releases/tag/v2.3.1) mention Yarn Project Files, so maybe I need to create one of those? But it's not documented what to name it or where to put it.

Thanks for your time and for the library 😘

**Comment by krispya** [comment]
Here is an example, but I can't get it to work for the life of me either.
https://github.com/YarnSpinnerTool/YarnSpinner/tree/1fae2a59f8b910495354709d574635f2c7896729/YarnSpinner.LanguageServer.Tests/TestData/TestWorkspace/Project2
