### ISSUE TITLE
yarn function comments are being truncated to the first line

### ISSUE THREAD

**Issue by McJones** [YarnSpinnerTool/YarnSpinner#378]
As it currently stands any document comments on a YarnFunction attributed method are slurped up and presented by the LSP when you hover over the function in a Yarn file.
However the hover is being truncated to the first line.

See attached
<img width="791" alt="Screen Shot 2023-11-24 at 1 46 34 pm" src="https://github.com/YarnSpinnerTool/YarnSpinner/assets/1658310/4614f241-9727-4e00-bbef-0057fb419c9f">
<img width="559" alt="Screen Shot 2023-11-24 at 1 46 43 pm" src="https://github.com/YarnSpinnerTool/YarnSpinner/assets/1658310/1ee86ae5-941f-46ee-93be-64999e7f0b9c">

**Comment by desplesda** [comment]
Looking at the tooltip, it looks like it's truncating at the XML tag, rather than at the end of the line.
