### ISSUE TITLE
Improve the "Extending" docs

### ISSUE THREAD

**Issue by bpicolo** [YarnSpinnerTool/YarnSpinner#55]
Hey guys,

Great library! This has made bootstrapping a dialogue system for my game much easier! Awesome.
Wanted to call this out because it took me some trial and error to figure out:
https://github.com/thesecretlab/YarnSpinner/blob/master/Documentation/Extending.md  is sneaky!
That's like, the best feature of the whole library and it's sort of tucked away.

The only reference I found to it was here:
https://github.com/thesecretlab/YarnSpinner/blob/master/Documentation/Usage.md#functions

but that suggests you can only run function in "if" statements, which seems to not be the case.
This becomes a super great DSL very fast. For me I now have just:
<<AcceptQuest()>> and that's awesome (much more powerful than the commands because you don't have to rely on global game objects).

Anyway, wanted to call out that the docs could use a quick addition or two to call attention to how good this bit is. : )

**Comment by desplesda** [comment]
This is something @PeteLawler is working on, I think! :) I'll assign this issue to him, and he can close it when he feels the documentation is looking better.

**Comment by PeteLawler** [comment]
A new parser is being implemented that'll make extending Yarn Spnner easier. It's hoped that this new parser will appear in the development branch by the end of June 2017. Once it's there, the Extending documentation will be updated to match the new parser.

**Comment by McJones** [comment]
There hasn’t been any activity on this in a while so I am closing this issue.
We still have a lot of docs work to go, but for now this is closed.
Please open a new issue for anything other docs issues.
