### ISSUE TITLE
Easy Setup for Open systems

### ISSUE THREAD

**Issue by PeteLawler** [YarnSpinnerTool/YarnSpinner#57]
Documentation, including the Easy Setup in README.md is heavily closed system centric (Windows, OSX) because of Unity focus. No discussion seems to be provided on how to build on linux/*bsd, except providing a claim that it's doable (afaict only a Unity demonstration is provided, nothing is provided for Open system). In fact, request for improvements to documentation in the README.md link directly to a UNITY.md file.
I'd like to propose that I drop by Secret Labs' office early next month and spend a few days addressing this. As such, I'd like to leave this as a meta-issue for now.

**Comment by PeteLawler** [comment]
I'd say the 'biggest' problem so far is that Unity is required to build any sort of demo, and Unity for Linux is huge and not a stable target.
MonoDevelop provide a flatpak so that's at least a known target. It might be an idea to suggest to Unity that they look at moving to flatpak as well.
Would still be good to have a simple sample game that doesn't require Unity.

**Comment by PeteLawler** [comment]
Having established that installing xbuild and nuget for building Yarn Spinner on Linux, as well as cleaning up the build scripts, having separate documents now for Yarn Spinner with Unity (a master, a quick guide for those familiar and a step by step) and API documentation generation (withouth commenting on the quality of said documentation level itself), I'm by and large content with the state of the setup for Open systems.

I'm mindful that the Step By Step needs to be improved, and there remains an situation with no demo available that doesn't involve Unity. However, I think things are now a vast improvement compared to the start of the year.

**Comment by rcuddy** [comment]
If anyone is curious, the build steps for Linux do seem to work as expected inside bash on windows subsystem for linux on windows 10 as well.

**Comment by PeteLawler** [comment]
@rcuddy I hadn't thought of checking for that, thanks heaps for letting us know!

**Comment by rcuddy** [comment]
@PeteLawler Actually, I may have spoken too soon! It -builds- fine, but I couldn't work out how to make it build a 3.5 compatible dll so unity couldn't load the output file. YarnSpinnerConsole worked as expected though.

I've just done a fresh install of windows so I'll try getting the wsl build working again, and document steps needed.

Also Rider (Jetbrains IDE) on windows works and builds the 3.5 assembly as expected so I'll document that too.

**Comment by rcuddy** [comment]
Okay, I give up, I was going to try to expand the documentation on this; I have a nice shiny fresh WSL and a nice shiny fresh ubuntu 17.04 and I can't get an old enough version of mono installed / compiled to be able to build 3.5 assemblies. I'm not sure what magic you guys have jumped through to make the old versions work, it's beyond my level of experience. Sorry :(

**Comment by desplesda** [comment]
Closing this, because as of v1.0 we use the `dotnet` toolchain to build YarnSpinner.dll and YarnSpinner.Compiler.dll, and the Unity components are distributed as source. If there are specific bugs with DLLs that are built with Linux, please file them as separate issues. Thank you! :heart:
