### ISSUE TITLE
Save/Load functionality.

### ISSUE THREAD

**Issue by bowlercaptain** [YarnSpinnerTool/YarnSpinner#60]
It would be useful to be able to save and later resume the state of a dialogue.

This can be done if the DialogueRunner Sourcetext is the same, and the DialogueRunner.dialogue.vm.state is stored and restored.

Ideally, the outside user would see a Save(string fileName="main") and a ResumeDialogue(string fileName="main") mimicking the behaviour of StartDialogue().

Calling Save() should wrap the state into an easily storable format, and then sent to the user's VariableStorageBehaviour with some relatively well-namespaced tag including the filename ("YarnStateSave$fileName"?)

For encapsulation's sake, State() should serialize and deserialize itself, VM and Dialogue should agnostically hand this up to DR.

**Comment by desplesda** [comment]
JSON is probably a decent place to start with the format. Yarn Spinner already has a dependency that provides JSON support, so we wouldn't need to add one. 

Any such format would also need to store some kind of version information, near the start of the data, so that a future version of the code can recognise it by seeing if it starts with (for example) "{v:1"

**Comment by bowlercaptain** [comment]
So I've noticed there's already a Jsonparser in the project, which appears to use a whole bunch of reflection to get things done. Would you recommend I figure those out enough to use them or throw together/unpack an Idictionary and use ToJson/FromJson?

**Comment by desplesda** [comment]
JsonParser is removed in the development branch - instead, it uses JSON.Net (http://www.newtonsoft.com/json).

**Comment by bowlercaptain** [comment]
Wrote this, PRed here: https://github.com/thesecretlab/YarnSpinner/pull/65

Will do testing/cleanup after lunch.

**Comment by desplesda** [comment]
Closed in #65 and #66.

**Comment by bowlercaptain** [comment]
Save system does not work across nodes (Virtualmachine currentNode is not initialized.) I can run SetNode()-like commands in DeserializeVM to fix this problem, or move CurrentNode to the state object (if that would work) however: will this break trying to save/load across different dialogue files? The system seems to understand having multiple files loaded to choose from, but where does this - ultimately state data - live? Is there a clean way to require that users have every relevant node loaded, if we can even support it?

**Comment by desplesda** [comment]
Is this solvable by throwing an error when you load a saved state that involves a node that is not loaded?

**Comment by McJones** [comment]
This was done as part of https://github.com/YarnSpinnerTool/YarnSpinner-Unity/pull/51 as such I am going to close this issue.
Thanks to everyone who participated.
