### ISSUE TITLE
YarnSpinnerConsole won't load under Linux MonoDevelop

### ISSUE THREAD

**Issue by PeteLawler** [YarnSpinnerTool/YarnSpinner#70]
When loading YarnSpinner.sln into the MonoDevelop FlatPak, we get
> Error while trying to load the project '/path/to/YarnSpinner/YarnSpinnerConsole/YarnSpinnerConsole.csproj': Object reference not set to an instance of an object

And nothing can be done on the YarnSpinnerConsole.

No real indication as to what's causing the problem right now.

**Comment by PeteLawler** [comment]
Seems this is only a problem on the master branch, development seems fine. Given #78 is suggesting a merge from development to master, it's probably best to wait for that process to complete before addressing this.

**Comment by McJones** [comment]
Unfortunately the Console got a bit behind the core of the project.
We are working on updating the console but that will require a hefty rewrite of the Console so it won’t happen until after 1.1 release.

I am closing this now but if you have any other issues with the console please mention them in issue #175 to keep it all in one place.
