### ISSUE TITLE
unit tests fail on master branch

### ISSUE THREAD

**Issue by PeteLawler** [YarnSpinnerTool/YarnSpinner#78]
I suspect this is happening because Master and Development have diverged too much and the CS project can't anymore. After chatting with @desplesda he is in agreement that this is most likely the issue and as such, the best solution will be to update Master with Development code rather than hacking on Master to force the unit test to pass. He has not given a schedule for this, beyond 'it won't happen this week'.

As such, unit tests are disabled on Travis building. Users are currently encouraged to unit test themselves and are requested to not file bugs referencing the following:

> 
> 1) Error : YarnSpinner.Tests.DialogueTests.TestAnalysis
> System.MissingMethodException : Method 'Yarn.Analysis.Context..ctor' not found.
>   at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
>   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0 
> 
> 2) Error : YarnSpinner.Tests.DialogueTests.TestNodeVistation
> System.MissingMethodException : Method 'Yarn.Dialogue.set_visitedNodes' not found.
>   at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
>   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0 
> 
> 3) Error : YarnSpinner.Tests.ProjectTests.TestLoadingSingleFile
> System.TypeLoadException : Could not resolve type with token 0100003a
>   at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
>   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0

**Comment by McJones** [comment]
I believe this is now fixed, so I am closing this issue.
If the issue reappears please open a new issue.
