### ISSUE TITLE
Set up Unity editor tests.

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnSpinner#8]
The demo game is written in Unity, which supports automated testing. It should be easy enough to write editor tests for the Unity parts of the project.

**Comment by Schroedingers-Cat** [comment]
I didn't know of this issue when working on this so I'm adding the references in here: e03418a922d7c322394b00b9d4ce677ceab31aae, https://github.com/YarnSpinnerTool/YarnSpinner/pull/244

**Comment by desplesda** [comment]
I’ll close this now, since it’s merged into `develop`. Thank you!
