### ISSUE TITLE
Localisation 'YarnSpinnerConsole.exe' standalone

### ISSUE THREAD

**Issue by PeteLawler** [YarnSpinnerTool/YarnSpinner#83]
Currently when running YarnSpinnerConsole.exe to generate localisation files, we've been doing this from our own personal build environments.
Given the target market for Yarn Spinner is authors, not programmers, it'd be highly useful to have a standalone tool that is a simple drag and drop type solution outside of the entire Unity package for authors to create the files to be translated.
Chatted with Jon about this and he agreed it's a desirable enhancement.

**Comment by lmsonic** [comment]
I would like this too, building it on windows is a mess! 
Monodevelop isn't available on windows so i have to build that too! Please do this

**Comment by McJones** [comment]
Unfortunately the Console got a bit behind the core of the project.
We are working on updating the console but that will require a hefty rewrite of the Console so it won’t happen until after 1.1 release.

I am closing this for now but for this or any other issues with the console please mention them in issue #175 to keep it all in one place.
