### ISSUE TITLE
Shouldn't be Yarn.Value class serializable?

### ISSUE THREAD

**Issue by oscar91** [YarnSpinnerTool/YarnSpinner#86]
Hola!

I'm making my save system for my game, and I ended up adding the [System.Serializable] on Value.cs, in order to store the variables from my dialogues in a binary file.

Is it wrong to make it serializable? Has it any disadvantage?

Thanks :)

**Comment by McJones** [comment]
We are working on a saving system thanks to naNuke which should resolve this.
It will hopefully be ready soon after 1.1 releases.
As this is effectively resolved I am closing this.

**Comment by desplesda** [comment]
It looks like this didn’t make it in to 1.1 - I’ll reopen the issue, so I can track it.

**Comment by desplesda** [comment]
I went to see about making `Yarn.Value` a protobuf, and then I started to wonder if we'd be better served by replacing the `Yarn.Value` class with the `Value` class provided by ProtoBuf. It serves the same function (a container for strings, numbers, bools, or null), is already serializable, and we wouldn't be duplicating the work. (We could probably remove the `Operand` type as well, but that's a tangential discussion.)

**Comment by DavidNightcap** [comment]
Seems reasonable to not duplicate work. It should probably work for what I'm doing at least as well as long as I can swap out Yarn.Value.
I'm using this to serialize a Dictionary<string, Yarn.Value> to disk:
https://assetstore.unity.com/packages/tools/input-management/easy-save-the-complete-save-load-asset-768

Also, I see you moved this to v2.0.  Any ETA on this one?  Thanks so much and wish I could help more on the coding side.  I've at least been promoting YS to the masses instead haha.

**Comment by desplesda** [comment]
v1.2 will likely stay in beta until at least early next week, to give people time to check it out. After that, we’ll reorganise the repos (#246), and begin the work of 2.0, which I don’t have a date for, but expect it to be at the very least a month or two away.

**Comment by DavidNightcap** [comment]
I know you're hard at work on this and it's not been 2 months yet, but I'm trying to put together a project roadmap for my game with the goal of submitting a QA'd build to Nintendo in December.  Do you think this feature would be done 3-4 months before that?  If not, I can look into modifying my current version of YS and compiling it in, but I'd rather stay up to date with the main trunk version. Thanks again for all the hard work!

**Comment by radiatoryang** [comment]
I see on develop branch that ``Yarn.Value`` is now an internal class for v2.0? How will that interact with serializing values in YarnSpinner-Unity, are the variables going to be part of the VM state so there's no longer any need to serialize separately?

**Comment by desplesda** [comment]
Internally, the VM stores values as `Yarn.Value`, which is now internal to the `YarnSpinner.dll` assembly. The `IVariableStorage` interface (which `InMemoryVariableStorage` implements) works directly with the types. There's no longer a reason to think about serialising the `Yarn.Value` class.

**Comment by desplesda** [comment]
Closing this issue because the change to `Value`'s visibility means this issue no longer applies.
