### ISSUE TITLE
Need a way to call a node and return to the next spot in execution

### ISSUE THREAD

**Issue by rcuddy** [YarnSpinnerTool/YarnSpinner#92]
It would be very useful if it were possible to call a node, run that node, then return back to where you called it from ie:

```
title: Start
---
<<set $hygiene = 0 >>
Day 1 Starts
[[MorningRoutine]]
Show some more text. Do more things.
[[Day2]]
===
title: Day2
---
Day 2 Starts
[[MorningRoutine]]
I hope today goes better.
[[End]]
===
title: MorningRoutine
---
I'm some content that can be shown repeatedly inline and called from different blocks.
-> Brush Teeth
  <<set $hygiene += 1 >>
-> Don't Brush Teeth
  <<set $hygiene -= 1 >>
===
title: End
---
<< if $hygiene > 0 >>
You win!
<<else>>
You have died of gingivitis.
<< endif >>
===
```

Would be great as it would allow things like room descriptions, recurring choices, etc to be handled without copy pasting or having to create custom commands to call these labels manually as if it was some sort of player interaction.

**Comment by desplesda** [comment]
I like this idea a lot.

Do you have a suggestion for what the syntax could look like?

**Comment by Hybrosia** [comment]
How about a simple <<return>>. That returns you to the node you were previously on.

**Comment by desplesda** [comment]
I like the simplicity, but having a "go back to the last node" operation means we'd need to always keep track of the last node in case we end up having to go back. A "go to this node and then come back here when it completes" operation means that we'd only need to track that state on demand.

**Comment by rcuddy** [comment]
Well, we already have the context of [[SomeNode]] being an auto node that is followed without user interaction. It'd be nice if you could use that same syntax, and we only need to track the jump if this line has lines after, so we'd just need to look ahead to see if node is complete before the jump.

If that's too much effort and people think it's better to have an explicit call command, then just something like:
<< call('node') >>

or going with Hybrosia's syntax
<NodeName> inside the calling node instead of the destination node still flags it as something slightly different, though I reckon that might cause some havoc with the tokeniser?

Or maybe [[Node<<]] or [[<<Node]] to flag the node as go and return?

Keeping a [[]] based syntax would allow for Yarn to handle drawing the flowchart without much work done that side.

**Comment by rcuddy** [comment]
Also, I'm happy to poke at actually implementing this if other people's tasks are currently higher priority. If it's agreed that it's a useful functionality for the project as a whole I'll spend time trying to make this work this weekend as I need it for a current project. Assuming consensus on syntax!

**Comment by desplesda** [comment]
Awesome. Let's figure out the syntax and behaviour here!

As is a separate point to the syntax, we're currently in the process of moving to a new ANTLR-based parser (see @McJones' work on the feature/ANTLR branch.) The advantage here is that modifying the grammar of the language to support features like this is made much easier. Just a heads-up for any planned editing of the parser!

**Comment by McJones** [comment]
So I really like the idea, not sure exactly what the syntax would be but I would be very hesitant to add more functionality to the already overloaded chevrons `< >` as they are used for so much.

I like the idea of some variant on the existing option syntax `[[...]]` but personally I would want some sort of change to it just to avoid people accidentally creating this embedded structure by placing an option above another line of dialogue.

One possible solution is to use the hashtag functionality on option, currently hashtags are only around for localisation and we are intentionally not allowing custom ones so we can add new functionality to lines if and when we need them.
So could define a new hashtag `#embed` and apply that to any inline options you want, so modifying @rcuddy's example from above:

```
title: Start
---
<<set $hygiene = 0 >>
Day 1 Starts
[[MorningRoutine]] #embed
Show some more text. Do more things.
[[Day2]]
===
title: Day2
---
Day 2 Starts
[[MorningRoutine]] #embed
I hope today goes better.
[[End]]
===
title: MorningRoutine
---
I'm some content that can be shown repeatedly inline and called from different blocks.
-> Brush Teeth
  <<set $hygiene += 1 >>
-> Don't Brush Teeth
  <<set $hygiene -= 1 >>
===
title: End
---
<< if $hygiene > 0 >>
You win!
<<else>>
You have died of gingivitis.
<< endif >>
===
```

My old C programmer brain is saying the easiest thing to do is to just dump the text of the _MorningRoutine_ node straight into the space where we want it embedded.
Regardless of how this ends up being done, when it comes to implementation of this there are a few different things to work out:
- does this count _MorningRoutine_ as having been visited?
- do we allow nested embedding?
- what keyword do we use?
- do we report we are in a different node or are we still inside the calling node?

Thoughts?

**Comment by desplesda** [comment]
My thoughts on @McJones's questions:

* Yes, I'd count the node you've just run as having been listed.
* Yes, I'd allow nesting this behaviour. All we'd need to do is maintain a stack of return addresses.
* Dunno if a keyword is the best thing here - more on that below.
* I'd report that we're in a different node.
* We don't currently detect or report on the cycles that are possible already (example: Node A can say `[[NodeB]]`, and Node B can say `[[NodeA]]`. If we add cycle detection, I don't think it would need to have any special considerations for this functionality.

As far as syntax goes, I'd like to keep any syntax inside the `[[ ]]` brackets; if it's outside, there's less of a visual indication that we're modifying the standard behaviour of jumping to a node.

My proposal is to introduce a new token, `<-`, and use it like so:

`[[RunThisNodeAndComeBackHere <-]]`

**Comment by McJones** [comment]
I'd argue that `<-` is a keyword but that's an aside... my reasoning for using a hashtag is:
- tokeniser, parser, and compiler already know how to read them
- keeping the syntax outside the `[[...]]` means no changes to the Yarn editor to visualise the connections (a guess, I could be wrong)
- if the plan is to eventually move over to ANTLR by adding syntax inside the `[[...]]` we limit the potential character space available for node names (which is currently everything except whitespace).
- if people are using the localisation features they have already seen the hashtag in use
- `<-` is comprised of two already heavily used symbols, adding additional complexity to the tokeniser.

Adding new syntax adds new work to each step, the tokeniser, the parser, the compiler, and the writer all now have to change/do more. With a hashtag only the compiler and the writer has to change.

In my mind this feature isn't so much a new functionality but a tweak to an existing one, exactly what the hashtags are meant to do, or are they only for localisation? If they are only to be for localisation why does the current setup handle them as if they are a generic thing?

I guess my main concern is every time a new feature is added the approach seems to go "just overload an existing syntax with a new keyword/special symbol" which doesn't sit well in my head and feels like it will end with YarnSpinner being comprised of loads of special symbol, edge cases that have to be handled in editors and compilers, and hard to read yarn files, which is something I'd try to avoid.

**Comment by rcuddy** [comment]
FWIW from my only recent familiarity with the library:

- Yes node should count as visited
- Nesting is what the writer would assume. It does complicate unwinding the stack a bit, but would be more powerful than not allowing.
- Keywords - outside of my experience with the platform
- It definitely should count as a different node! Do we need to expose a way to find out what the node we came here from was though?
- Cycles - outside of my experience with the platform

I definitely agree with the [[NodeName <-]] syntax. Something that looks like existing content, but modified to show the idea of flowing backwards. Easily read in script mode, easily parsed into existing Yarn editor.

**Comment by McJones** [comment]
oops pressed the wrong button.. reopened.

**Comment by desplesda** [comment]
Yeah, I get @McJones' point about adding more complexity to the grammar, especially when the situation inside delimited areas is already quite busy. (For example, after a `<<` or `[[`, the parser has to be very careful to correctly identify whether the following text is raw text.)

Additionally, because we're in the middle of updating the parser already, making a change like this right now could induce some headaches.

Some of this work is independent of the syntax, and it looks like we all agree on how it should behave. The only contention is the syntax.

To that end, I suggest we make the compiler add support for diverting to a node and returning when it exits; I think that @McJones is right that we can use the existing syntactic support for hashtags to access this experimental feature, and once the parser has settled down, look at what a more visually pleasing syntax would involve.

How's that sound?

**Comment by rcuddy** [comment]
Hashtag support seems like it opens up other future custom logic paths in end user space, so that works for me!

The term itself being `#embed` makes sense if we're dumping the content into the compiled flow inline, but if we're handling it as it's own node state with "visited", and reporting that we've actually transitioned to a new node,  perhaps something like `#call` might be more semantically in line with what it's doing?

Thanks for taking this suggestion on board, btw, I didn't expect it to get any interest.

**Comment by desplesda** [comment]
Some thoughts on verb choice:

* `#return`
* `#comeback`
* `#divert`
* `#call`
* `#detour`

**Comment by rcuddy** [comment]
Further query on functionality; can you have an option choice also be a call out and return? I'd expect you to have the choices presented, you pick one, and then come back to the line after choice group, and not be presented with the same choices again.

```
title: Start
---
What should I do today?
[[Go to the Mall | GoToMall]] #return
[[Go to the Park | GoToPark]] #return
A: Glad that's over.
Some more stuff in this node and then we're out.
...
[[Day2]]
===
title: Day2
---
...
That strange man told me I should go to the park, but the other one said I should go to the mall.
[[Go to the Mall | GoToMall]] #return
[[Go to the Park | GoToPark]] #return
What an adventure.
[[End]]
===
title: GoToMall
---
This bit never changes. The mall stands tall and proud....
<< if $secret_mall_base_found = true >>
But wait, there's the secret door the old man mentioned!
<< else >>
Guess I'll go back home.
<< endif>>
===
title: GoToPark
---
This bit never changes. The park is quite and relaxing.
<< if $secret_portal_found = true >>
But wait, there's the gateway to Arcadia the old man mentioned!
<< else >>
Guess I'll go back home.
<< endif>>
===
```
I'm struggling to think of an example of why we would be needing to present a list of reusable call outs to chose from that wouldn't just be node changes out right, hence the weak example, but I have a feeling that it's something someone will use cleverly if it's there.

Also, as I  type this it occurs to me that repeating choices could be handled in a return block with no special overloading.


```
title: Start
---
What should I do today?
[[DayChoices]] #return
A: Glad that's over.
Some more stuff in this node and then we're out.
===
title: DayChoices
---
[[Go to the Mall | GoToMall]]
[[Go to the Park | GoToPark]]
===
```
Then we get proper node jumps from the choice menu, but the choice menu itself is the call and return; which we then unwind from at the end of GoToMall or GoToPark.

Yes/no?

Have started working through the VirtualMachine and the compiler code. I think we'll need a new ByteCode type for this special returner node as it's -not- a choice group with one option that is jumping, it's slightly different.

```
[[CallOutBlock1]] #return
[[CallOutBlock2]] #return
[[Go To School|GoToSchool]]
[[Go To Library|GoToLibrary]]
```
This would be two independent call and returns followed by an options dialogue with 2 choices, then then terminate this node. This would, I think, require keeping them outside of the grouping of currentOptions and put into their own thing, though the jumping logic of a single unlabeled choice is similar.

Kind of thinking out loud into this box now, so I might stop now.

**Comment by desplesda** [comment]
Options wrapped in `[[` and `]]` are only presented at the end of the node, so there's no real gain in having it "come back". However, what we've discussed in this thread can be combined with shortcut options, which _do_ present options and then continue:

````
What should I do today?
-> Go to the mall
    [[GoToMall]] #return
-> Go to the park
    [[GoToPark]] #return

**Comment by McJones** [comment]
I reckon @desplesda's answer above is The Way It Should Be Done™.
As I appear to have become the "hmm do we really need more?" Guy, I think adding more functionality to the options when shortcuts already support this/will when returning options work with minimal typing a WAY better idea.
Additionally this lets you group any other content (I'm thinking changing some variables) needed before the jump, together as part of the shortcut blocks.

Personally other than it is just too convenient to have the `[[Go to the mall|GotToMall]]` form I would make options ALWAYS jump (and probably rename them as well...) and just use shortcuts as the way to present choice to the users.

**Comment by rcuddy** [comment]
Oh, of course, I forgot about that short form arrow syntax. That makes my first example silly. I definitely like the short form as shown in @desplesda 's sample.  I may have jumbled some terminology, apologies, I'll need to brush up a bit more on the differences there.

If we assume a group of [[Label|Node]] blocks have to end a node that makes things less challenging.

@McJones if I read your 2nd para correctly, are you suggesting the removal of the [[Label|Node]] syntax and enforcing the use of -> for choices, leaving only [[Node]] syntax for node changes?

**Comment by McJones** [comment]
Yeah, if I was sole arbiter of the language I would completely change a whole bunch of things, wasn't being particularly serious about that, if nothing else the current way of handling options is very convenient.
Probably for the best I am not the sole arbiter really, YarnSpinner would probably just end up looking like lua...

**Comment by desplesda** [comment]
Quick note @rcuddy added support for this feature before we completed our migration to the ANTLR-based parser, and we weren't able to merge that PR due to the ANTLR changeover, but this is still something that I think we'd all like to see.

**Comment by rcuddy** [comment]
I've had this in the back of my head for ages but not had time for any passion projects lately. Been getting the itch to do something with yarn again, especially now that it's hit 1.* releases, so I might try to brush up on antlr and the new VM system and see if i can make this happen in the next couple of months but if anyone else wants to do it, feel free by all means

**Comment by Haapavuo** [comment]
Yes, please merge #return to master! We would greatly appreciate it, thanks!

**Comment by TheMartianLife** [comment]
Moved to #303 to reflect changed in YS since this proposal.
